// Generated by scripts/generate-blog-data.mts. Edit Markdown files under content/blog instead.
export const blogPosts = [
  {
    "slug": "reviewable-drone-sports-decisions",
    "publishedAt": "2026-09-13",
    "author": "Velocity Lab Innovation",
    "coverImage": "/media/vli-hero-video-first-frame_6e981c30.jpg",
    "title": {
      "en": "Why Reviewable Decisions Matter in Drone Sports",
      "zh-Hant": "為何可覆核判決對無人機運動至關重要"
    },
    "description": {
      "en": "A practical guide for organisers who want faster, more consistent, and more reviewable drone-sports decisions.",
      "zh-Hant": "為希望提升無人機運動判決速度、一致性及可覆核性的主辦方而設的實用指南。"
    },
    "category": {
      "en": "Event operations",
      "zh-Hant": "賽事營運"
    },
    "body": {
      "en": "# Why Reviewable Decisions Matter in Drone Sports\n\nWhen a close call interrupts a match, the operational cost is larger than the disputed moment. Officials need time to reconstruct what happened, teams need confidence that the same standard will be applied, and organisers need a clear record that can be explained after the event.\n\nA reviewable decision layer helps the event move from **“what did the referee see?”** to **“what does the evidence show?”**. The goal is not to remove human judgement from the competition. It is to give officials a consistent reference that supports timely calls, calm reviews, and a stronger participant experience.\n\n## Start with the event workflow\n\nBefore selecting equipment, map the venue, ruleset, match format, and review process. A useful system should fit the way your event already operates, while making the most difficult moments easier to resolve.\n\n## Build confidence through evidence\n\nA replayable decision record can help organisers explain a call to teams, jury members, and partners. It also gives the production team a repeatable way to identify where delays occur and where the event format can be improved.\n\n## Make the next event easier to run\n\nThe strongest technology is the technology that becomes part of the run sheet. Define who prepares the markers, who monitors the system, who reviews a close call, and how the final record is retained. That clarity turns a technical capability into an operational advantage.\n\nIf you are planning a competition, share your venue, ruleset, and schedule with the VLI team. We can help shape a practical configuration around the event you are actually delivering.",
      "zh-Hant": "# 為何可覆核判決對無人機運動至關重要\n\n當一次接近界線的判決打斷比賽時，營運成本往往不只是一個爭議時刻。裁判需要時間重建現場情況，隊伍需要確信相同標準會被一致採用，而主辦方亦需要一份能在賽後清楚解釋的紀錄。\n\n可覆核的判決層，能讓賽事由**「裁判看到了甚麼？」**轉向**「證據顯示了甚麼？」**。這並不是要取代裁判的人工作判，而是提供一致的參考依據，支援及時判決、平靜覆核，以及更可靠的參賽體驗。\n\n## 先從賽事流程開始\n\n在選擇設備前，先整理場地、規則、賽制及覆核流程。一套實用的系統應配合您現有的賽事運作方式，同時令最難處理的時刻更容易解決。\n\n## 以證據建立信心\n\n可重播的判決紀錄，有助主辦方​​向隊伍、評審團成員及合作夥伴解釋判決，亦讓製作團隊能以一致方法找出延誤來源及改善賽事形式。\n\n## 令下一場賽事更容易執行\n\n最有價值的科技，是能真正融入執行清單的科技。清楚界定誰負責準備標記、監察系統、覆核爭議判決，以及保存最終紀錄，便能將技術能力轉化為營運優勢。\n\n如您正在規劃比賽，歡迎向 VLI 團隊提供場地、規則及時間表資料。我們可以按您實際執行的賽事，協助制定可行配置。"
    }
  }
] as const;
