// Generated by scripts/generate-bundle-data.mts. Edit Markdown files under content/bundles (and the Bundles table in content/pricing.md) instead.
export type BundleContentRecord = {
  id: string;
  order: number;
  visible: boolean;
  featured: boolean;
  title: { en: string; "zh-Hant": string };
  tagline: { en: string; "zh-Hant": string };
  price: string;
  priceNote: { en: string; "zh-Hant": string };
  optionPrice?: string;
  optionPriceNote: { en: string; "zh-Hant": string };
  cta: { en: string; "zh-Hant": string };
  image: string;
  imageAlt: { en: string; "zh-Hant": string };
  summary: { en: string; "zh-Hant": string };
  includes: { en: string[]; "zh-Hant": string[] };
};
export const bundleContent: readonly BundleContentRecord[] = [
  {
    "id": "stem-classroom-kit",
    "order": 1,
    "visible": true,
    "featured": false,
    "title": {
      "en": "STEM Classroom Kit",
      "zh-Hant": "STEM 課室套裝"
    },
    "tagline": {
      "en": "Primary & junior secondary",
      "zh-Hant": "小學及初中"
    },
    "price": "HK$8,180",
    "priceNote": {
      "en": "Class set for 6 groups · includes teacher training and printed lesson materials",
      "zh-Hant": "6 組課室套裝 · 包括教師培訓及印刷教材"
    },
    "optionPrice": "HK$14,780",
    "optionPriceNote": {
      "en": "Double class set (12 drones) · about 3% off equipment",
      "zh-Hant": "雙倍課室套裝（12 部無人機）· 器材約 97 折"
    },
    "cta": {
      "en": "Request a school quotation",
      "zh-Hant": "索取學校報價"
    },
    "image": "/media/Droneequipment_2ab6c2b7.jpg",
    "imageAlt": {
      "en": "TOPS Shield 200 brushed drone soccer sets for a school STEM class",
      "zh-Hant": "供學校 STEM 課堂使用的 TOPS 飛盾 200 空心杯足球無人機套裝"
    },
    "summary": {
      "en": "A safe first step into drone soccer for STEM lessons: lightweight brushed drones in protective cages, enough batteries for a full lesson, and a teacher who knows how to run it.",
      "zh-Hant": "以安全方式在 STEM 課堂引入無人機足球：附保護球殼的輕巧空心杯無人機、足夠一堂課使用的電池，並由導師教老師如何帶領課堂。"
    },
    "includes": {
      "en": [
        "6× TOPS Shield 200 Brushed RTF sets (one per group)",
        "18× TOPS Shield 200 2S 450 mAh flight batteries (3 per drone)",
        "1× 10-port USB charger",
        "6× TOPS drone carry bags (20 cm)",
        "2-hour on-site teacher training: setup, flight safety and running a class",
        "Lesson pack: 4 lesson plans, student worksheets and safety rules",
        "Free access to the VLI drone soccer [Score Board](/scoreboard) for class matches",
        "30-day warranty against manufacturing defects",
        "Itemised quotation for school procurement and funding applications"
      ],
      "zh-Hant": [
        "6 套 TOPS 飛盾 200 空心杯 RTF 套裝（每組一套）",
        "18 粒 TOPS 飛盾 200 2S 450 mAh 飛行電池（每部 3 粒）",
        "1 部 10 埠 USB 充電器",
        "6 個 TOPS 無人機收納包（20 公分）",
        "2 小時到校教師培訓：設定、飛行安全及課堂帶領",
        "教材套：4 份教案、學生工作紙及安全守則",
        "免費使用 VLI 無人機足球[記分板](/scoreboard)進行課堂比賽",
        "30 日製造缺陷保養",
        "提供分項報價，方便學校採購及申請資助"
      ]
    }
  },
  {
    "id": "school-team-pack",
    "order": 2,
    "visible": true,
    "featured": true,
    "title": {
      "en": "School Competition Team Pack",
      "zh-Hant": "學校競賽隊伍套裝"
    },
    "tagline": {
      "en": "Secondary school team",
      "zh-Hant": "中學校隊"
    },
    "price": "HK$26,140",
    "priceNote": {
      "en": "One full 5-drone F9A team · 5% off equipment, coach training included",
      "zh-Hant": "一隊 5 部 F9A 無人機 · 器材 95 折，已包括教練培訓"
    },
    "optionPriceNote": {
      "en": "",
      "zh-Hant": ""
    },
    "cta": {
      "en": "Request a school quotation",
      "zh-Hant": "索取學校報價"
    },
    "image": "/manus-storage/excel_prod_30_a7d07b66.png",
    "imageAlt": {
      "en": "TOPS Shield 205 brushless competition drone set for a school team",
      "zh-Hant": "供學校隊伍使用的 TOPS Shield 205 無刷競賽無人機套裝"
    },
    "summary": {
      "en": "Everything a school needs to field its own drone soccer team and enter inter-school competitions, with drones tuned by VLI and a full year of repair cover.",
      "zh-Hant": "學校組建自己的無人機足球隊並參加校際比賽所需的一切：無人機由 VLI 調校，並附一整年維修保障。"
    },
    "includes": {
      "en": [
        "5× TOPS Shield 205 brushless RTF sets, Tier 2 VLI-verified: checked, PID-tuned, 21-day warranty",
        "1-year VLI-CARE on all 5 drones: accidental damage, collisions and free repair, up to two replacements each",
        "20× OVONIC 4S 1080 mAh 110C LiPo batteries (4 per drone)",
        "2× D6 PRO dual-channel smart chargers",
        "5× TOPS drone carry bags (20–22 cm)",
        "4-hour on-site coach training: team flying, tactics, battery safety and basic repairs",
        "Free access to the VLI drone soccer [Score Board](/scoreboard) for training matches",
        "Itemised quotation for school procurement and funding applications"
      ],
      "zh-Hant": [
        "5 套 TOPS Shield 205 無刷 RTF 套裝，Tier 2 VLI 驗證：檢測、PID 調校，21 日保養",
        "5 部無人機均附一年 VLI-CARE：意外損壞、碰撞及免費維修，每部最多兩次更換",
        "20 粒 OVONIC 4S 1080 mAh 110C LiPo 電池（每部 4 粒）",
        "2 部 D6 PRO 雙通道智能充電器",
        "5 個 TOPS 無人機收納包（20–22 公分）",
        "4 小時到校教練培訓：隊伍飛行、戰術、電池安全及基本維修",
        "免費使用 VLI 無人機足球[記分板](/scoreboard)進行練習賽",
        "提供分項報價，方便學校採購及申請資助"
      ]
    }
  },
  {
    "id": "host-school-arena",
    "order": 3,
    "visible": true,
    "featured": false,
    "title": {
      "en": "Host School Arena Pack",
      "zh-Hant": "主辦學校場地套裝"
    },
    "tagline": {
      "en": "Whole-school programme & inter-school events",
      "zh-Hant": "全校計劃及校際賽事"
    },
    "price": "HK$61,830",
    "priceNote": {
      "en": "Two full teams plus arena · 8.5% off equipment, training and event day included",
      "zh-Hant": "兩隊無人機連場地 · 器材減 8.5%，已包括培訓及賽事日支援"
    },
    "optionPriceNote": {
      "en": "",
      "zh-Hant": ""
    },
    "cta": {
      "en": "Request a school quotation",
      "zh-Hant": "索取學校報價"
    },
    "image": "/manus-storage/excel_prod_8_903cb396.png",
    "imageAlt": {
      "en": "Inflatable 6 × 3 × 3 m drone soccer arena for a school hall",
      "zh-Hant": "適用於學校禮堂的 6 × 3 × 3 米充氣式無人機足球場"
    },
    "summary": {
      "en": "Turn the school hall into a drone soccer venue: two full teams, a full-size inflatable arena and a charging station, so your school can run its own programme and host inter-school matches.",
      "zh-Hant": "把學校禮堂變成無人機足球場：兩隊完整無人機、標準大小的充氣式球場及充電站，讓學校自行推行計劃並主辦校際比賽。"
    },
    "includes": {
      "en": [
        "10× TOPS Shield brushless RTF sets (5× TOPS Shield 205 + 5× TOPS Shield 220), Tier 2 VLI-verified",
        "1-year VLI-CARE on all 10 drones",
        "1× inflatable drone soccer arena (6 × 3 × 3 m) with blower",
        "40× OVONIC 4S 1080 mAh 110C LiPo batteries (4 per drone)",
        "Charging station: 1× TA300 8-channel smart charger and 2× D6 PRO dual-channel chargers",
        "10× TOPS drone carry bags (20–22 cm)",
        "8 hours of on-site training for teachers and student technical crew",
        "First inter-school event day supported by a VLI technical official, run on the free [Score Board](/scoreboard)",
        "Optional [Smart Referee](/dronesportsreferee) video review for your event, quoted separately",
        "Itemised quotation for school procurement and funding applications"
      ],
      "zh-Hant": [
        "10 套 TOPS Shield 無刷 RTF 套裝（5 套 TOPS Shield 205 + 5 套 TOPS Shield 220），Tier 2 VLI 驗證",
        "10 部無人機均附一年 VLI-CARE",
        "1 個充氣式無人機足球場（6 × 3 × 3 米）連鼓風機",
        "40 粒 OVONIC 4S 1080 mAh 110C LiPo 電池（每部 4 粒）",
        "充電站：1 部 TA300 八通道智能充電器及 2 部 D6 PRO 雙通道充電器",
        "10 個 TOPS 無人機收納包（20–22 公分）",
        "8 小時到校培訓，對象為老師及學生技術團隊",
        "首場校際賽事由 VLI 技術裁判支援，使用免費[記分板](/scoreboard)運作",
        "可選加 [Smart Referee](/dronesportsreferee) 賽事影片覆核，另行報價",
        "提供分項報價，方便學校採購及申請資助"
      ]
    }
  }
];
