// Generated by scripts/generate-bundle-data.mts. Edit Markdown files under content/bundles (and the Bundles table in content/pricing.md) instead.
export type BundleContentRecord = {
  id: string;
  order: number;
  visible: boolean;
  featured: boolean;
  title: { en: string; "zh-Hant": string };
  tagline: { en: string; "zh-Hant": string };
  price: string;
  priceNote: { en: string; "zh-Hant": string };
  optionPrice?: string;
  optionPriceNote: { en: string; "zh-Hant": string };
  cta: { en: string; "zh-Hant": string };
  image: string;
  imageAlt: { en: string; "zh-Hant": string };
  summary: { en: string; "zh-Hant": string };
  includes: { en: string[]; "zh-Hant": string[] };
};
export const bundleContent: readonly BundleContentRecord[] = [
  {
    "id": "classroom-starter",
    "order": 1,
    "visible": true,
    "featured": false,
    "title": {
      "en": "Classroom Starter Pack",
      "zh-Hant": "課室入門套裝"
    },
    "tagline": {
      "en": "Introductory STEM",
      "zh-Hant": "入門 STEM 教學"
    },
    "price": "HK$19,800",
    "priceNote": {
      "en": "One-time purchase",
      "zh-Hant": "一次性購買"
    },
    "optionPrice": "HK$23,800",
    "optionPriceNote": {
      "en": "Bundled with 1-year basic support (save 15%)",
      "zh-Hant": "連一年基本支援（節省 15%）"
    },
    "cta": {
      "en": "Request this bundle",
      "zh-Hant": "查詢此套裝"
    },
    "image": "/media/Droneequipment_2ab6c2b7.jpg",
    "imageAlt": {
      "en": "TOPS Shield 200 brushed drone soccer set for classroom use",
      "zh-Hant": "適用於課室的 TOPS 飛盾 200 空心杯足球無人機套裝"
    },
    "summary": {
      "en": "Everything a classroom needs to start drone soccer safely: lightweight brushed drones, plenty of flight time, and a ready-made lesson guide.",
      "zh-Hant": "課室開展無人機足球所需的一切：輕巧的空心杯無人機、充足的飛行時間，以及現成的教學指南。"
    },
    "includes": {
      "en": [
        "4× TOPS Shield 200 Brushed RTF sets",
        "12× 1S LiPo flight batteries",
        "1× 10-port USB charger",
        "Digital student learning guide (flight basics and safety rules)",
        "30-day warranty against manufacturing defects"
      ],
      "zh-Hant": [
        "4 套 TOPS 飛盾 200 空心杯 RTF 套裝",
        "12 粒 1S LiPo 飛行電池",
        "1 部 10 埠 USB 充電器",
        "學生數碼學習指南（飛行基礎及安全守則）",
        "30 日製造缺陷保養"
      ]
    }
  },
  {
    "id": "competition-team",
    "order": 2,
    "visible": true,
    "featured": true,
    "title": {
      "en": "Competition Team Pack",
      "zh-Hant": "競賽隊伍套裝"
    },
    "tagline": {
      "en": "The core offering",
      "zh-Hant": "核心方案"
    },
    "price": "HK$46,800",
    "priceNote": {
      "en": "Hardware",
      "zh-Hant": "硬件"
    },
    "optionPrice": "HK$10,800",
    "optionPriceNote": {
      "en": "per year · Team Support SLA",
      "zh-Hant": "每年 · 隊伍支援服務協議（SLA）"
    },
    "cta": {
      "en": "Request this bundle",
      "zh-Hant": "查詢此套裝"
    },
    "image": "/manus-storage/excel_prod_30_a7d07b66.png",
    "imageAlt": {
      "en": "TOPS Shield 205 brushless competition drone set",
      "zh-Hant": "TOPS Shield 205 無刷競賽無人機套裝"
    },
    "summary": {
      "en": "A full five-drone competition squad with the arena, power, and support to train and compete all season.",
      "zh-Hant": "完整的五機競賽隊伍配置，連同場地、電源及支援，讓隊伍全季訓練及參賽。"
    },
    "includes": {
      "en": [
        "5× TOPS Shield 205 brushless Striker sets (open-source flight controller with tuned PID profiles)",
        "20× 4S 1100 mAh LiPo batteries",
        "2× dual-channel smart field chargers",
        "1× inflatable drone soccer arena (6 × 3 × 3 m) with blower",
        "Professional multi-protocol transmitters, configured for ELRS",
        "1-year priority maintenance: 3-day repair turnaround and free diagnostic checks",
        "4 hours of on-site instructor training and flight optimisation"
      ],
      "zh-Hant": [
        "5 套 TOPS Shield 205 無刷主攻手套裝（開源飛控，已調校 PID 設定）",
        "20 粒 4S 1100 mAh LiPo 電池",
        "2 部雙通道智能場地充電器",
        "1 個充氣式無人機足球場（6 × 3 × 3 米）連鼓風機",
        "專業多協議遙控器，已設定 ELRS",
        "一年優先維修：3 日維修周轉及免費檢測",
        "4 小時到場導師培訓及飛行優化"
      ]
    }
  },
  {
    "id": "full-arena",
    "order": 3,
    "visible": true,
    "featured": false,
    "title": {
      "en": "Full Arena & Tournament System",
      "zh-Hant": "全場地及賽事系統"
    },
    "tagline": {
      "en": "Enterprise / scale",
      "zh-Hant": "企業／大型規模"
    },
    "price": "From HK$128,000",
    "priceNote": {
      "en": "One-time setup · bespoke quotation from our sales team",
      "zh-Hant": "一次性建置 · 由銷售團隊度身報價"
    },
    "optionPriceNote": {
      "en": "",
      "zh-Hant": ""
    },
    "cta": {
      "en": "Request a bespoke quotation",
      "zh-Hant": "索取度身報價"
    },
    "image": "/media/flex13camerasys_aa73a4e5.jpg",
    "imageAlt": {
      "en": "Smart Referee camera system set up around a drone soccer arena",
      "zh-Hant": "設置於無人機足球場周圍的 Smart Referee 攝影系統"
    },
    "summary": {
      "en": "A turnkey venue and officiating system for schools, clubs, and organisers running recurring tournaments.",
      "zh-Hant": "為定期舉辦賽事的學校、會所及主辦方而設的一站式場地及裁判系統。"
    },
    "includes": {
      "en": [
        "10× TOPS Shield 205/220 brushless competition drones",
        "2× events with the integrated [Smart Referee](/dronesportsreferee) setup, including calibrated video playback",
        "Central match control software with real-time score display and automated timing buzzer ([try the free Score Board](/scoreboard))",
        "40× flight batteries and a safe LiPo charging station",
        "Full-year comprehensive maintenance, including bi-monthly on-site safety audits"
      ],
      "zh-Hant": [
        "10 部 TOPS Shield 205／220 無刷競賽無人機",
        "2 場賽事的整合式 [Smart Referee](/dronesportsreferee) 設置，包括經校準的影片重播",
        "中央賽事控制軟件，具即時比分顯示及自動計時蜂鳴器（[免費試用記分板](/scoreboard)）",
        "40 粒飛行電池及安全 LiPo 充電站",
        "全年全面維修保養，包括每兩個月一次到場安全審核"
      ]
    }
  }
];
