// Generated by scripts/generate-product-data.mts. Edit content/pricing.md instead.
export const refereePackagePrices = {
  "assist": "From HK$6,800",
  "managed": "From HK$11,800",
  "evidence-pro": "From HK$16,800"
} as const;
