// Generated by scripts/generate-product-data.mts. Edit Markdown files under content/products instead.
export type ProductVariantContentRecord = {
  id: string;
  label: string;
  name: string;
  model: string;
  price: string;
  tier1Price: string;
  tier2Price?: string;
  vliCarePrice?: string;
  tier1MinQty?: number;
  tier?: string;
  image: string;
  imageAlt: string;
};
export type ProductDetailContentRecord = {
  familyId: string;
  order: number;
  visible: boolean;
  title: { en: string; "zh-Hant": string };
  category: { en: string; "zh-Hant": string };
  description: { en: string; "zh-Hant": string };
  variants: ProductVariantContentRecord[];
  defaultTier?: string;
  vliCareTiers: string[];
  detail?: {
    en: { platformLabel: string; premiumTitle: string; careTitle: string; careDescription: string; specificationsTitle: string; inTheBoxTitle: string; equipmentTierPartsLabel: string; equipmentTierPartsDescription: string; equipmentTierVerifiedLabel: string; equipmentTierVerifiedDescription: string; careAddOnTitle: string; careAddOnDescription: string; tiers: Record<string, { label: string; subtitle: string; features: string[]; inTheBox: string[] }>; specifications: Array<[string, string]>; inTheBox: string[] };
    "zh-Hant": { platformLabel: string; premiumTitle: string; careTitle: string; careDescription: string; specificationsTitle: string; inTheBoxTitle: string; equipmentTierPartsLabel: string; equipmentTierPartsDescription: string; equipmentTierVerifiedLabel: string; equipmentTierVerifiedDescription: string; careAddOnTitle: string; careAddOnDescription: string; tiers: Record<string, { label: string; subtitle: string; features: string[]; inTheBox: string[] }>; specifications: Array<[string, string]>; inTheBox: string[] };
  };
};
export const productContent: readonly ProductDetailContentRecord[] = [
  {
    "familyId": "tops-shield-205",
    "order": 1,
    "visible": true,
    "title": {
      "en": "TOPS Shield 205",
      "zh-Hant": "TOPS Shield 205"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "Flying Shield 205 Brushless Soccer Drone, F9A-B Striker drone, designed for tournament competition. Features modular DIY-assembled cage, upgraded FC and motors for enhanced speed and power output. Upgraded shell material: thickened and stiffened for superior impact resistance! Open-source FC compatible with professional transmitters. Available in RTF and PNP versions to suit beginners and pro players alike.",
      "zh-Hant": "飛盾205無刷球機，F9A-B主攻手球機，專為錦標賽設計，球殼可DIY組裝，飛控電機升級，速度提升，動力加碼～升級球殼材質，加厚加硬更耐撞擊！開源飛控，可適配各種專業遙控，有套裝和單球版，滿足初學者和專業級玩家的不同需求。"
    },
    "variants": [
      {
        "id": "25",
        "label": "RTF",
        "name": "TOPS Shield 205 RTF",
        "model": "TZ009",
        "price": "HK$2,430",
        "tier1Price": "HK$2,430",
        "tier2Price": "HK$3,430",
        "vliCarePrice": "HK$560",
        "tier1MinQty": 2,
        "tier": "certified",
        "image": "/manus-storage/excel_prod_30_a7d07b66.png",
        "imageAlt": "TOPS Shield 205 competition drone kit box"
      },
      {
        "id": "26",
        "label": "PNP",
        "name": "TOPS Shield 205 PNP",
        "model": "TZ009",
        "price": "HK$1,900",
        "tier1Price": "HK$1,900",
        "tier2Price": "HK$2,900",
        "vliCarePrice": "HK$560",
        "tier1MinQty": 2,
        "tier": "builder",
        "image": "/manus-storage/excel_prod_31_93c6811c.png",
        "imageAlt": "TOPS Shield 205 PNP competition drone product image"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "205 mm platform",
        "premiumTitle": "TOPS Shield 205: The Agile Striker",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "Tier 1 · PARTS only",
        "equipmentTierPartsDescription": "Parts-only supply with a limited warranty up to 7 days.",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI-verified",
        "equipmentTierVerifiedDescription": "The drone is checked and reported, then PID-tuned to its finest performance, with a 21-day warranty.",
        "careAddOnTitle": "Add VLI-CARE",
        "careAddOnDescription": "a 1-year plan with up to 2 replacements and free repair for accidental damage, user error, collisions, water damage, and flyaway incidents. Submit a repair request through support email; shipping is not included.",
        "tiers": {
          "builder": {
            "label": "PNP (+ELRS)",
            "subtitle": "For teams with in-house technicians.",
            "features": [],
            "inTheBox": [
              "1x Drone soccer aircraft body"
            ]
          },
          "certified": {
            "label": "RTF",
            "subtitle": "Plug-and-play for professional arenas and schools.",
            "features": [],
            "inTheBox": [
              "1x Drone soccer aircraft",
              "1x Remote controller",
              "1x Battery",
              "1x Accessory pack"
            ]
          }
        },
        "specifications": [
          [
            "Dimensions",
            "205mm diameter"
          ],
          [
            "Weight",
            "200g (w/o battery) / 267g (with battery)"
          ],
          [
            "Flight Time",
            "8 mins (hover)"
          ],
          [
            "Motor",
            "1404 (or 1407) Brushless Motor"
          ],
          [
            "Wheelbase",
            "110mm"
          ],
          [
            "Battery",
            "1100mAh 11.1V 3S 60C LiPo"
          ],
          [
            "Carbon Plate Thickness",
            "3mm"
          ],
          [
            "Propeller",
            "75mm 3-blade"
          ],
          [
            "LED",
            "Color-tunable LED + smart light controller"
          ],
          [
            "Other Functions",
            "Self-leveling, adjustable cage LED, orientation taillights (headless mode, turtle mode, semi-stable/acro mode software adjustable)"
          ],
          [
            "Colour Options",
            "White, Red, Blue"
          ]
        ],
        "inTheBox": []
      },
      "zh-Hant": {
        "platformLabel": "205 毫米平台",
        "premiumTitle": "TOPS Shield 205：靈活進攻平台",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "Tier 1 · 僅零件",
        "equipmentTierPartsDescription": "僅供應零件，有限保養期最長 7 天。",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI 驗證",
        "equipmentTierVerifiedDescription": "無人機會經過檢查及報告，並進行 PID 微調至最佳性能，保養期 21 天。",
        "careAddOnTitle": "加購 VLI CARE",
        "careAddOnDescription": "一年附加計劃：最多兩次更換及免費維修，涵蓋意外損壞、操作失誤、碰撞、進水及飛失事故。請透過支援電郵提交維修申請；運費不包括在內。",
        "tiers": {
          "builder": {
            "label": "無人機足球 (僅無人機)",
            "subtitle": "適合具備內部技術人員的隊伍。",
            "features": [],
            "inTheBox": [
              "1x 球機機體"
            ]
          },
          "certified": {
            "label": "RTF全家桶",
            "subtitle": "適合專業場地及學校的即插即用配置。",
            "features": [],
            "inTheBox": [
              "1x 球機",
              "1x 遙控",
              "1x 電池",
              "1x 配件包"
            ]
          }
        },
        "specifications": [
          [
            "外形尺寸",
            "205直徑"
          ],
          [
            "機身重量",
            "200g（不含電池）/267g（含電池）"
          ],
          [
            "飛行時間",
            "8分鐘（懸停）"
          ],
          [
            "電機",
            "無刷電機 1404（或1407）"
          ],
          [
            "軸距",
            "110mm"
          ],
          [
            "電池",
            "1100mAh 11.1V 3S 60C 鋰電池"
          ],
          [
            "碳板厚度",
            "3mm"
          ],
          [
            "螺旋槳",
            "75mm 3葉槳葉"
          ],
          [
            "LED",
            "可調色LED+智能燈控"
          ],
          [
            "其他功能",
            "自穩、可調節球體燈光、姿態尾燈（無頭模式、反烏龜，半自穩、手動模式都可軟件調節）"
          ],
          [
            "顏色",
            "白、紅、藍可選"
          ]
        ],
        "inTheBox": []
      }
    }
  },
  {
    "familyId": "tops-shield-220",
    "order": 2,
    "visible": true,
    "title": {
      "en": "TOPS Shield 220",
      "zh-Hant": "TOPS Shield 220"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "Features a high-elasticity protective cage engineered against shattering. Flexible composite material combines high resilience, impact resistance, and lightweight structure. Aerodynamic profile maximizes flight endurance. Brushless motors deliver high thrust and extreme agility. Racing 3-blade propellers ensure rapid acceleration. Precision gimbals, integrated touch display, and frequency-hopping ensure low latency and rock-solid connection. Available in RTF and PNP configurations.",
      "zh-Hant": "這是一款具有強大彈性的護罩，不會輕易碎裂，靈活的防護罩複合材料具有高彈性、抗衝擊性和重量輕的特點。空氣動力學設計最大限度地延長了飛行時間。無刷電機提供強大的性能和極致的飛行性能。使用賽車專用的三翼螺旋槳實現更快的飛行。體驗更刺激的無人機飛行。精確的控制桿、集成的觸控顯示屏和多通道跳頻提供了低功耗和可靠的連接。有套裝和單球版，滿足初學者和專業級玩家的不同需求。"
    },
    "variants": [
      {
        "id": "27",
        "label": "RTF",
        "name": "TOPS Shield 220 RTF",
        "model": "TZ002",
        "price": "HK$2,430",
        "tier1Price": "HK$2,430",
        "tier2Price": "HK$3,430",
        "vliCarePrice": "HK$560",
        "tier1MinQty": 2,
        "tier": "certified",
        "image": "/manus-storage/excel_prod_9_417b350f.png",
        "imageAlt": "TOPS Shield 220 competition drone cage illustration"
      },
      {
        "id": "28",
        "label": "RTF + Bag",
        "name": "TOPS Shield 220 RTF + Bag",
        "model": "TZ002",
        "price": "HK$2,650",
        "tier1Price": "HK$2,650",
        "tier2Price": "HK$3,650",
        "vliCarePrice": "HK$560",
        "tier1MinQty": 2,
        "tier": "travel",
        "image": "/manus-storage/excel_prod_21_68f8cfe7.png",
        "imageAlt": "TOPS Shield 220 drone with remote controller"
      },
      {
        "id": "29",
        "label": "PNP",
        "name": "TOPS Shield 220 PNP",
        "model": "TZ002",
        "price": "HK$1,900",
        "tier1Price": "HK$1,900",
        "tier2Price": "HK$2,900",
        "vliCarePrice": "HK$560",
        "tier1MinQty": 2,
        "tier": "builder",
        "image": "/manus-storage/excel_prod_24_65d1f683.png",
        "imageAlt": "TOPS Shield 220 PNP competition drone cage diagram"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "220 mm platform",
        "premiumTitle": "TOPS Shield 220: The Competition Workhorse",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "Tier 1 · PARTS only",
        "equipmentTierPartsDescription": "Parts-only supply with a limited warranty up to 7 days.",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI-verified",
        "equipmentTierVerifiedDescription": "The drone is checked and reported, then PID-tuned to its finest performance, with a 21-day warranty.",
        "careAddOnTitle": "Add VLI-CARE",
        "careAddOnDescription": "Optional Tier 2 add-on: a 1-year plan with up to 2 replacements and free repair for accidental damage, user error, collisions, water damage, and flyaway incidents. Submit a repair request through support email; shipping is not included.",
        "tiers": {
          "certified": {
            "label": "RTF",
            "subtitle": "Ready-to-fly for competition teams and schools.",
            "features": [],
            "inTheBox": [
              "1x Drone soccer aircraft body",
              "4x 1404 brushless motor",
              "1x 4-in-1 35A ESC",
              "1x Open-source FC",
              "1x Remote controller",
              "1x 3S 1100mAh LiPo battery",
              "1x A40 charger",
              "1x Multi-purpose screwdriver",
              "1x Accessory pack"
            ]
          },
          "travel": {
            "label": "RTF + Travel Bag",
            "subtitle": "Ready-to-fly with a transport bag for touring programmes.",
            "features": [],
            "inTheBox": [
              "1x Drone soccer aircraft body",
              "4x 1404 brushless motor",
              "1x 4-in-1 35A ESC",
              "1x Open-source FC",
              "1x Remote controller",
              "1x 3S 1100mAh LiPo battery",
              "1x A40 charger",
              "1x Multi-purpose screwdriver",
              "1x Accessory pack",
              "1x Carrying bag"
            ]
          },
          "builder": {
            "label": "PNP (+ELRS)",
            "subtitle": "PNP platform for teams with their own control system.",
            "features": [],
            "inTheBox": [
              "1x Drone soccer aircraft body",
              "4x 1404 brushless motor",
              "1x 4-in-1 35A ESC",
              "1x Open-source FC"
            ]
          }
        },
        "specifications": [
          [
            "Dimensions",
            "220*220*220mm"
          ],
          [
            "Weight",
            "172g (w/o battery) / 241g (with battery)"
          ],
          [
            "Flight Time",
            "8 mins (hover)"
          ],
          [
            "Motor",
            "1404 Brushless Motor"
          ],
          [
            "Wheelbase",
            "130mm"
          ],
          [
            "Battery",
            "1100mAh 11.1V 3S 60C LiPo"
          ],
          [
            "Carbon Plate Thickness",
            "3mm"
          ],
          [
            "Propeller",
            "60mm 3-blade"
          ],
          [
            "LED",
            "Color-tunable LED + smart light controller"
          ],
          [
            "Other Functions",
            "Self-leveling, adjustable cage LED, orientation taillights (headless mode, turtle mode, semi-stable/acro mode software adjustable)"
          ],
          [
            "Colour Options",
            "White, Red, Blue"
          ]
        ],
        "inTheBox": []
      },
      "zh-Hant": {
        "platformLabel": "220 毫米平台",
        "premiumTitle": "TOPS Shield 220：競賽主力平台",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "Tier 1 · 僅零件",
        "equipmentTierPartsDescription": "僅供應零件，有限保養期最長 7 天。",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI 驗證",
        "equipmentTierVerifiedDescription": "無人機會經過檢查及報告，並進行 PID 微調至最佳性能，保養期 21 天。",
        "careAddOnTitle": "加購 VLI CARE",
        "careAddOnDescription": "僅適用於 Tier 2 的一年附加計劃：最多兩次更換及免費維修，涵蓋意外損壞、操作失誤、碰撞、進水及飛失事故。請透過支援電郵提交維修申請；運費不包括在內。",
        "tiers": {
          "certified": {
            "label": "RTF",
            "subtitle": "適合競賽隊伍及學校的開箱即飛配置。",
            "features": [],
            "inTheBox": [
              "1x 球機機體",
              "4x 1404無刷電機",
              "1x 4 in 1 35A 電調",
              "1x 開源飛控",
              "1x 遙控器",
              "1x 3S 1100mAh 鋰電池",
              "1x A40充電器",
              "1x 多用螺絲刀",
              "1x 配件包"
            ]
          },
          "travel": {
            "label": "RTF全家桶 + 便攜袋",
            "subtitle": "配備運輸袋，適合巡迴計劃的開箱即飛配置。",
            "features": [],
            "inTheBox": [
              "1x 球機機體",
              "4x 1404無刷電機",
              "1x 4 in 1 35A 電調",
              "1x 開源飛控",
              "1x 遙控器",
              "1x 3S 1100mAh 鋰電池",
              "1x A40充電器",
              "1x 多用螺絲刀",
              "1x 配件包",
              "1x 收納包"
            ]
          },
          "builder": {
            "label": "無人機足球 (僅無人機)",
            "subtitle": "適合使用自備控制系統的隊伍的 PNP 平台。",
            "features": [],
            "inTheBox": [
              "1x 球機機體",
              "4x 1404無刷電機",
              "1x 4 in 1 35A 電調",
              "1x 開源飛控"
            ]
          }
        },
        "specifications": [
          [
            "外形尺寸",
            "220*220*220mm"
          ],
          [
            "機身重量",
            "172g（不含電池）/241g（含電池）"
          ],
          [
            "飛行時間",
            "8分鐘（懸停）"
          ],
          [
            "電機",
            "無刷電機 1404"
          ],
          [
            "軸距",
            "130mm"
          ],
          [
            "電池",
            "1100mAh 11.1V 3S 60C 鋰電池"
          ],
          [
            "碳板厚度",
            "3mm"
          ],
          [
            "螺旋槳",
            "60mm 3葉槳葉"
          ],
          [
            "LED",
            "可調色LED+智能燈控"
          ],
          [
            "其他功能",
            "自穩、可調節球體燈光、姿態尾燈（無頭模式、反烏龜，半自穩、手動模式都可軟件調節）"
          ],
          [
            "顏色",
            "白、紅、藍可選"
          ]
        ],
        "inTheBox": []
      }
    }
  },
  {
    "familyId": "fb200-racer",
    "order": 3,
    "visible": false,
    "title": {
      "en": "FB200 Racer",
      "zh-Hant": "FB200 Racer"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "200 mm ready-to-fly racer with ball guard and essential flying kit.",
      "zh-Hant": "200 毫米開箱即飛競速機，配備球形保護架及基本飛行套裝。"
    },
    "variants": [
      {
        "id": "30",
        "label": "RTF",
        "name": "FB200 RTF Racer",
        "model": "FB200",
        "price": "HK$5,252",
        "tier1Price": "HK$5,252",
        "image": "/manus-storage/excel_prod_10_e5fc5653.png",
        "imageAlt": "FB200 RTF racer drone with remote controller"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "fb210-racer",
    "order": 4,
    "visible": false,
    "title": {
      "en": "FB210 Racer",
      "zh-Hant": "FB210 Racer"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "210 mm ready-to-fly ball drone with upgraded motor package and carry bag.",
      "zh-Hant": "210 毫米開箱即飛球形無人機，配備升級馬達套裝及攜行袋。"
    },
    "variants": [
      {
        "id": "31",
        "label": "RTF",
        "name": "FB210 RTF Racer",
        "model": "FB210",
        "price": "HK$5,993",
        "tier1Price": "HK$5,993",
        "image": "/manus-storage/excel_prod_11_fc95565c.png",
        "imageAlt": "FB210 RTF racer drone with remote controller"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "r200",
    "order": 5,
    "visible": false,
    "title": {
      "en": "R200",
      "zh-Hant": "R200"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "Compact 200 mm ball drone platform with 3S power setup.",
      "zh-Hant": "配備 3S 電源配置的緊湊型 200 毫米球形無人機平台。"
    },
    "variants": [
      {
        "id": "32",
        "label": "RTF",
        "name": "R200 RTF",
        "model": "R200",
        "price": "HK$5,590",
        "tier1Price": "HK$5,590",
        "image": "/manus-storage/excel_prod_13_712f9740.png",
        "imageAlt": "R200 RTF competition drone with remote controller"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "r200f",
    "order": 6,
    "visible": true,
    "title": {
      "en": "R200F",
      "zh-Hant": "R200F"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "F9A-B 200 mm brushless soccer drone, supplied ready to fly with a carrying bag. Suitable for the 2025 National Aeromodelling Championship, 2025 National Youth Aeromodelling Championship, 2025 China Drone Soccer League, 2025 World Drone Soccer Championship, and the 15th National Games.",
      "zh-Hant": "F9A-B 200 無刷足球無人機，連球包開箱即飛。適用於參加2025年全國航空航天模型錦標賽、2025年全國青少年航空航天模型錦標賽、2025年中國無人機足球聯賽、2025年世界無人機足球錦標賽、第十五屆全運會。"
    },
    "variants": [
      {
        "id": "33",
        "label": "RTF",
        "name": "R200F RTF",
        "model": "R200F",
        "price": "HK$3,650",
        "tier1Price": "HK$3,650",
        "tier2Price": "HK$4,650",
        "vliCarePrice": "HK$700",
        "tier1MinQty": 2,
        "tier": "certified",
        "image": "/manus-storage/excel_prod_15_cb880557.png",
        "imageAlt": "R200F RTF competition drone with remote controller"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "R200F platform",
        "premiumTitle": "R200F: The Compact Brushless Competition Kit",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "Tier 1 · PARTS only",
        "equipmentTierPartsDescription": "Parts-only supply with a limited warranty up to 7 days.",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI-verified",
        "equipmentTierVerifiedDescription": "The drone is checked and reported, then PID-tuned to its finest performance, with a 21-day warranty.",
        "careAddOnTitle": "Add VLI-CARE",
        "careAddOnDescription": "Optional Tier 2 add-on: a 1-year plan with up to 2 replacements and free repair for accidental damage, user error, collisions, water damage, and flyaway incidents. Submit a repair request through support email; shipping is not included.",
        "tiers": {
          "certified": {
            "label": "RTF",
            "subtitle": "Ready-to-fly kit with transmitter, receiver, charger, and carrying bag.",
            "features": [],
            "inTheBox": [
              "1x Drone aircraft",
              "1x Remote controller",
              "1x Receiver",
              "1x Charger",
              "1x Battery",
              "1x Handbag",
              "2 pairs Propellers"
            ]
          }
        },
        "specifications": [
          [
            "Outer Diameter",
            "200mm"
          ],
          [
            "Takeoff Weight",
            "257g"
          ],
          [
            "Voltage",
            "3-4S"
          ],
          [
            "Wheelbase",
            "103mm"
          ],
          [
            "Carbon Plate",
            "3.5mm"
          ],
          [
            "Motor",
            "Brushless MISS1407-3800KV"
          ],
          [
            "Battery",
            "15.2V 1120mAh"
          ],
          [
            "FC + ESC",
            "Open-source MR26-AIO-F411E35A"
          ],
          [
            "Propeller",
            "2.9 inch 3-blade"
          ],
          [
            "Light Control",
            "2CH smart light control + tunable LED"
          ],
          [
            "Flight Time",
            "> 4 mins"
          ],
          [
            "ELRS Transmitter",
            "ET01"
          ],
          [
            "Receiver",
            "ER01"
          ],
          [
            "Charger",
            "A400"
          ],
          [
            "Carrying Bag",
            "220mm drone handbag"
          ],
          [
            "Package Weight",
            "1800g"
          ],
          [
            "Package Dimensions",
            "398*245*240mm"
          ],
          [
            "Colour Options",
            "Red, Blue"
          ]
        ],
        "inTheBox": []
      },
      "zh-Hant": {
        "platformLabel": "R200F 平台",
        "premiumTitle": "R200F：緊湊型無刷競賽套裝",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "Tier 1 · 僅零件",
        "equipmentTierPartsDescription": "僅供應零件，有限保養期最長 7 天。",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI 驗證",
        "equipmentTierVerifiedDescription": "無人機會經過檢查及報告，並進行 PID 微調至最佳性能，保養期 21 天。",
        "careAddOnTitle": "加購 VLI CARE",
        "careAddOnDescription": "僅適用於 Tier 2 的一年附加計劃：最多兩次更換及免費維修，涵蓋意外損壞、操作失誤、碰撞、進水及飛失事故。請透過支援電郵提交維修申請；運費不包括在內。",
        "tiers": {
          "certified": {
            "label": "RTF 全家桶",
            "subtitle": "包括遙控器、接收機、充電器及收納手提包的開箱即飛套裝。",
            "features": [],
            "inTheBox": [
              "1x 球機",
              "1x 遙控器",
              "1x 接收機",
              "1x 充電器",
              "1x 電池",
              "1x 手提包",
              "2對 槳葉"
            ]
          }
        },
        "specifications": [
          [
            "外徑",
            "200mm"
          ],
          [
            "起飛重量",
            "257g"
          ],
          [
            "電壓",
            "3-4S"
          ],
          [
            "軸距",
            "103mm"
          ],
          [
            "碳板",
            "3.5mm"
          ],
          [
            "電機",
            "無刷 MISS1407-3800KV"
          ],
          [
            "電池",
            "15.2V 1120mAh"
          ],
          [
            "飛控+電調",
            "開源 MR26-AIO-F411E35A"
          ],
          [
            "螺旋槳",
            "2.9寸三葉槳"
          ],
          [
            "燈控",
            "2CH智能燈控+可調LED"
          ],
          [
            "飛行時間",
            "大於4分鐘"
          ],
          [
            "ELRS遙控器",
            "ET01"
          ],
          [
            "接收機",
            "ER01"
          ],
          [
            "充電器",
            "A400"
          ],
          [
            "收納手提包",
            "220mm球機手提包"
          ],
          [
            "包裝重量",
            "1800g"
          ],
          [
            "包裝尺寸",
            "398*245*240mm"
          ],
          [
            "顏色",
            "紅、藍2色可選"
          ]
        ],
        "inTheBox": []
      }
    }
  },
  {
    "familyId": "r220f",
    "order": 7,
    "visible": true,
    "title": {
      "en": "R220F",
      "zh-Hant": "R220F"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "F9A-B 220 mm brushless soccer drone, supplied ready to fly with a carrying bag. Suitable for the 2025 National Aeromodelling Championship, 2025 National Youth Aeromodelling Championship, 2025 China Drone Soccer League, 2025 World Drone Soccer Championship, and the 15th National Games.",
      "zh-Hant": "F9A-B 220 無刷足球無人機，連球包開箱即飛。適用於參加2025年全國航空航天模型錦標賽、2025年全國青少年航空航天模型錦標賽、2025年中國無人機足球聯賽、2025年世界無人機足球錦標賽、第十五屆全運會。"
    },
    "variants": [
      {
        "id": "34",
        "label": "RTF",
        "name": "R220F RTF",
        "model": "R220F",
        "price": "HK$3,890",
        "tier1Price": "HK$3,890",
        "tier2Price": "HK$4,890",
        "vliCarePrice": "HK$700",
        "tier1MinQty": 2,
        "tier": "certified",
        "image": "/manus-storage/excel_prod_17_584dbd72.png",
        "imageAlt": "R220F RTF competition drone with remote controller"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "R220F platform",
        "premiumTitle": "R220F: The Ready-to-Deploy Training Platform",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "Tier 1 · PARTS only",
        "equipmentTierPartsDescription": "Parts-only supply with a limited warranty up to 7 days.",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI-verified",
        "equipmentTierVerifiedDescription": "The drone is checked and reported, then PID-tuned to its finest performance, with a 21-day warranty.",
        "careAddOnTitle": "Add VLI-CARE",
        "careAddOnDescription": "Optional Tier 2 add-on: a 1-year plan with up to 2 replacements and free repair for accidental damage, user error, collisions, water damage, and flyaway incidents. Submit a repair request through support email; shipping is not included.",
        "tiers": {
          "certified": {
            "label": "RTF",
            "subtitle": "Complete RTF setup for training, demonstration, and event support.",
            "features": [],
            "inTheBox": [
              "1x Drone aircraft",
              "1x Remote controller",
              "1x Receiver",
              "1x Charger",
              "1x Battery",
              "1x Handbag",
              "2 pairs Propellers"
            ]
          }
        },
        "specifications": [
          [
            "Outer Diameter",
            "220mm"
          ],
          [
            "Takeoff Weight",
            "299g"
          ],
          [
            "Voltage",
            "3-4S"
          ],
          [
            "Wheelbase",
            "115mm"
          ],
          [
            "Carbon Plate",
            "3.5mm"
          ],
          [
            "Motor",
            "Brushless MISS1407-3800KV"
          ],
          [
            "Battery",
            "15.2V 1120mAh"
          ],
          [
            "FC + ESC",
            "Open-source MR26-AIO-F411E35A"
          ],
          [
            "Propeller",
            "2.9 inch 3-blade"
          ],
          [
            "Light Control",
            "2CH smart light control + tunable LED"
          ],
          [
            "Flight Time",
            "> 4 mins"
          ],
          [
            "ELRS Transmitter",
            "ET01"
          ],
          [
            "Receiver",
            "ER01"
          ],
          [
            "Charger",
            "A400"
          ],
          [
            "Carrying Bag",
            "220mm drone handbag"
          ],
          [
            "Package Dimensions",
            "430*290*235mm"
          ],
          [
            "Colour Options",
            "Red, Blue"
          ]
        ],
        "inTheBox": []
      },
      "zh-Hant": {
        "platformLabel": "R220F 平台",
        "premiumTitle": "R220F：即時部署訓練平台",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "Tier 1 · 僅零件",
        "equipmentTierPartsDescription": "僅供應零件，有限保養期最長 7 天。",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI 驗證",
        "equipmentTierVerifiedDescription": "無人機會經過檢查及報告，並進行 PID 微調至最佳性能，保養期 21 天。",
        "careAddOnTitle": "加購 VLI CARE",
        "careAddOnDescription": "僅適用於 Tier 2 的一年附加計劃：最多兩次更換及免費維修，涵蓋意外損壞、操作失誤、碰撞、進水及飛失事故。請透過支援電郵提交維修申請；運費不包括在內。",
        "tiers": {
          "certified": {
            "label": "RTF 全家桶",
            "subtitle": "適合訓練、示範及賽事支援的完整 RTF 配置。",
            "features": [],
            "inTheBox": [
              "1x 球機",
              "1x 遙控器",
              "1x 接收機",
              "1x 充電器",
              "1x 電池",
              "1x 手提包",
              "2對 槳葉"
            ]
          }
        },
        "specifications": [
          [
            "外徑",
            "220mm"
          ],
          [
            "起飛重量",
            "299g"
          ],
          [
            "電壓",
            "3-4S"
          ],
          [
            "軸距",
            "115mm"
          ],
          [
            "碳板",
            "3.5mm"
          ],
          [
            "電機",
            "無刷 MISS1407-3800KV"
          ],
          [
            "電池",
            "15.2V 1120mAh"
          ],
          [
            "飛控+電調",
            "開源 MR26-AIO-F411E35A"
          ],
          [
            "螺旋槳",
            "2.9寸三葉槳"
          ],
          [
            "燈控",
            "2CH智能燈控+可調LED"
          ],
          [
            "飛行時間",
            "大於4分鐘"
          ],
          [
            "ELRS遙控器",
            "ET01"
          ],
          [
            "接收機",
            "ER01"
          ],
          [
            "充電器",
            "A400"
          ],
          [
            "收納手提包",
            "220mm球機手提包"
          ],
          [
            "包裝尺寸",
            "430*290*235mm"
          ],
          [
            "顏色",
            "紅、藍2色可選"
          ]
        ],
        "inTheBox": []
      }
    }
  },
  {
    "familyId": "tops-shield-400",
    "order": 8,
    "visible": true,
    "title": {
      "en": "TOPS Shield 400",
      "zh-Hant": "TOPS Shield 400"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "40cm full-size soccer drone, dedicated for competitive matches. Engineered through rigorous drone flight dynamics R&D and exhaustive flight testing. Delivers thrilling maneuverability and high power output, matching optimized hardware combinations for peak competitive performance. Striker series maximizes athletic responsiveness and tournament reliability.",
      "zh-Hant": "40公分大號足球無人機，專為比賽設計。通過對無人機運動的不斷研究、開發和無數次飛行測試，不僅以其動態機動性和強大的能量滿足用戶，還通過各種飛行測試和無數次練習賽研究遊戲的最佳設備組合，以最大限度地提高產品的性能。專為無人機足球開發的前鋒不僅通過其動態機動性和強大的能量提高了用戶的滿意度，而且我們還通過各種飛行測試和眾多練習賽研究了針對比賽優化的設備組合，以發揮產品的最佳性能。"
    },
    "variants": [
      {
        "id": "35",
        "label": "RTF",
        "name": "TOPS Shield 400 RTF",
        "model": "TZ003",
        "price": "HK$4,350",
        "tier1Price": "HK$4,350",
        "tier2Price": "HK$5,350",
        "vliCarePrice": "HK$950",
        "tier1MinQty": 2,
        "tier": "certified",
        "image": "/manus-storage/excel_prod_26_26e91f83.png",
        "imageAlt": "TOPS Shield 400 competition drone in a blue cage"
      },
      {
        "id": "36",
        "label": "PNP",
        "name": "TOPS Shield 400 PNP",
        "model": "TZ003",
        "price": "HK$3,510",
        "tier1Price": "HK$3,510",
        "tier2Price": "HK$4,510",
        "vliCarePrice": "HK$950",
        "tier1MinQty": 2,
        "tier": "builder",
        "image": "/manus-storage/excel_prod_19_2844a82e.png",
        "imageAlt": "TOPS Shield 400 PNP competition drone"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "400 mm platform",
        "premiumTitle": "TOPS Shield 400: The Arena-Scale Platform",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "Tier 1 · PARTS only",
        "equipmentTierPartsDescription": "Parts-only supply with a limited warranty up to 7 days.",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI-verified",
        "equipmentTierVerifiedDescription": "The drone is checked and reported, then PID-tuned to its finest performance, with a 21-day warranty.",
        "careAddOnTitle": "Add VLI-CARE",
        "careAddOnDescription": "Optional Tier 2 add-on: a 1-year plan with up to 2 replacements and free repair for accidental damage, user error, collisions, water damage, and flyaway incidents. Submit a repair request through support email; shipping is not included.",
        "tiers": {
          "certified": {
            "label": "RTF",
            "subtitle": "Ready-to-fly for larger-format matches and venue deployments.",
            "features": [],
            "inTheBox": [
              "1 set Protective outer cage",
              "1 set Carbon fiber center frame",
              "4x Brushless motor 2506 1960KV",
              "1x 50A 4-in-1 ESC (6S supported)",
              "1x Professional Drone Soccer FC",
              "1x POSITION LED",
              "1x REAR LED",
              "1x TEAM LED",
              "2 sets Propellers",
              "1 set ELRS remote controller"
            ]
          },
          "builder": {
            "label": "PNP (+ELRS)",
            "subtitle": "PNP platform for technical teams with their own electronics.",
            "features": [],
            "inTheBox": [
              "1x Drone soccer aircraft (receiver not included, sold separately)"
            ]
          }
        },
        "specifications": [
          [
            "Dimensions",
            "400*400*400mm"
          ],
          [
            "Weight",
            "1020g (with battery)"
          ],
          [
            "Flight Time",
            "6 mins (hover)"
          ],
          [
            "Motor",
            "2506 1960KV Brushless Motor"
          ],
          [
            "Flight Controller",
            "STRIKER V3 F435 FC"
          ],
          [
            "ESC",
            "STRIKER V3 55A"
          ],
          [
            "Battery",
            "4S 14.8V 120C 3000mAh LiPo (sold separately; 4S and 6S batteries supported)"
          ],
          [
            "BetaFlight",
            "Parameter tuning supported"
          ],
          [
            "LED",
            "Color-tunable LED + smart light controller"
          ],
          [
            "Other Functions",
            "Self-leveling, adjustable cage LED, orientation taillights (headless mode, turtle mode, semi-stable/acro mode software adjustable)"
          ],
          [
            "Colour Options",
            "Red, White, Blue"
          ]
        ],
        "inTheBox": []
      },
      "zh-Hant": {
        "platformLabel": "400 毫米平台",
        "premiumTitle": "TOPS Shield 400：場館級平台",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "Tier 1 · 僅零件",
        "equipmentTierPartsDescription": "僅供應零件，有限保養期最長 7 天。",
        "equipmentTierVerifiedLabel": "Tier 2 · VLI 驗證",
        "equipmentTierVerifiedDescription": "無人機會經過檢查及報告，並進行 PID 微調至最佳性能，保養期 21 天。",
        "careAddOnTitle": "加購 VLI CARE",
        "careAddOnDescription": "僅適用於 Tier 2 的一年附加計劃：最多兩次更換及免費維修，涵蓋意外損壞、操作失誤、碰撞、進水及飛失事故。請透過支援電郵提交維修申請；運費不包括在內。",
        "tiers": {
          "certified": {
            "label": "RTF 全家桶",
            "subtitle": "適合較大規模賽事及場館部署的開箱即飛配置。",
            "features": [],
            "inTheBox": [
              "1套 保護外殼",
              "1套 碳纖中心機架",
              "4x 無刷電機2506 1960KV",
              "1x 50A 4 in 1電調（支持6S）",
              "1x 專業無人機足球飛控",
              "1x POSITION LED",
              "1x REAR LED",
              "1x TEAM LED",
              "2套 螺旋槳",
              "1套 ELRS版遙控器"
            ]
          },
          "builder": {
            "label": "PNP 僅無人機 (+ELRS)",
            "subtitle": "適合使用自備電子設備的技術隊伍的 PNP 平台。",
            "features": [],
            "inTheBox": [
              "1x 球機（不含接收機，接收機另配）"
            ]
          }
        },
        "specifications": [
          [
            "外形尺寸",
            "400*400*400mm"
          ],
          [
            "機身重量",
            "1020g（含電池）"
          ],
          [
            "飛行時間",
            "6分鐘（懸停）"
          ],
          [
            "電機",
            "2506 1960KV 無刷電機"
          ],
          [
            "飛控",
            "前鋒 V3 F435 FC"
          ],
          [
            "電調",
            "STRIKER V3 55A"
          ],
          [
            "電池",
            "4S 14.8V 120C 3000mAh鋰電池（電池另配，4S、6S電池均可）"
          ],
          [
            "BetaFlight",
            "支持調參"
          ],
          [
            "LED",
            "可調色LED+智能燈控"
          ],
          [
            "其他功能",
            "自穩、可調節球體燈光、姿態尾燈（無頭模式、反烏龜，半自穩、手動模式都可軟件調節）"
          ],
          [
            "顏色",
            "紅、白、藍可選"
          ]
        ],
        "inTheBox": []
      }
    }
  },
  {
    "familyId": "ace-lipo-battery",
    "order": 9,
    "visible": true,
    "title": {
      "en": "ACE LiPo Battery",
      "zh-Hant": "ACE LiPo 電池"
    },
    "category": {
      "en": "Drone power",
      "zh-Hant": "無人機電源"
    },
    "description": {
      "en": "Gens ACE LiPo batteries for drone soccer and FPV racing. The 3S 11.1V 1100mAh pack suits 200 and 220 brushless soccer drones; the 4S and 6S 3000mAh 120C packs suit 400 brushless soccer drones.",
      "zh-Hant": "格氏ACE鋰電池，適用於足球無人機及穿越機。3S 11.1V 1100mAh 適用於200或220無刷球機；4S及6S 3000mAh 120C 適用於400無刷球機。"
    },
    "variants": [
      {
        "id": "69",
        "label": "3S · 1100 mAh",
        "name": "ACE 3S 1100 mAh Battery",
        "model": "3S battery",
        "price": "HK$144",
        "tier1Price": "HK$144",
        "image": "/manus-storage/excel_prod_3_aa72f902.png",
        "imageAlt": "ACE 3S 1100 mAh LiPo battery"
      },
      {
        "id": "70",
        "label": "4S · 3000 mAh",
        "name": "ACE 4S 3000 mAh Battery",
        "model": "4S battery",
        "price": "HK$330",
        "tier1Price": "HK$330",
        "image": "/manus-storage/excel_prod_27_854f107d.png",
        "imageAlt": "ACE 4S 3000 mAh LiPo battery"
      },
      {
        "id": "71",
        "label": "6S · 3000 mAh",
        "name": "ACE 6S 3000 mAh Battery",
        "model": "6S battery",
        "price": "HK$477.60",
        "tier1Price": "HK$477.60",
        "image": "/manus-storage/excel_prod_28_5edbfa4d.png",
        "imageAlt": "ACE 6S 3000 mAh LiPo battery"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "3S 11.1V 1100mAh",
            "For 200 or 220 brushless soccer drones and FPV racing drones; 68g; 60*28*20mm"
          ],
          [
            "4S 3000mAh 120C",
            "For 400 brushless soccer drones and FPV racing drones"
          ],
          [
            "6S 3000mAh 120C",
            "22.2V, 6S1P, XT60; for 400 brushless soccer drones and FPV racing drones"
          ]
        ],
        "inTheBox": [
          "1x Battery (selected version)"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "3S 11.1V 1100mAh",
            "200或者220無刷球機、穿越機用；68g；60*28*20mm"
          ],
          [
            "4S 3000mAh 120C",
            "400無刷球機用、穿越機用"
          ],
          [
            "6S 3000mAh 120C",
            "22.2V，6S1P，XT60；400無刷球機用、穿越機用"
          ]
        ],
        "inTheBox": [
          "1x 電池（所選型號）"
        ]
      }
    }
  },
  {
    "familyId": "usb-charger",
    "order": 10,
    "visible": false,
    "title": {
      "en": "10-Port USB Charger",
      "zh-Hant": "10 埠 USB 充電器"
    },
    "category": {
      "en": "Charging equipment",
      "zh-Hant": "充電設備"
    },
    "description": {
      "en": "Multi-port USB charger for compatible battery workflows.",
      "zh-Hant": "適用於兼容電池流程的多埠 USB 充電器。"
    },
    "variants": [
      {
        "id": "75",
        "label": "10-port",
        "name": "10-Port USB Charger",
        "model": "10-port USB charger",
        "price": "HK$117",
        "tier1Price": "HK$117",
        "image": "/manus-storage/excel_prod_6_81781e24.png",
        "imageAlt": "10-port white USB charger"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "b3-balance-charger",
    "order": 11,
    "visible": false,
    "title": {
      "en": "B3 Balance Charger",
      "zh-Hant": "B3 平衡充電器"
    },
    "category": {
      "en": "Charging equipment",
      "zh-Hant": "充電設備"
    },
    "description": {
      "en": "Compact balance charger options for 2S and 3S LiPo batteries.",
      "zh-Hant": "適用於 2S 及 3S LiPo 電池的緊湊型平衡充電器選項。"
    },
    "variants": [
      {
        "id": "76",
        "label": "20 W",
        "name": "B3 20W Balance Charger",
        "model": "B3 20W",
        "price": "HK$65",
        "tier1Price": "HK$65",
        "image": "/manus-storage/excel_prod_1_f4a517d6.png",
        "imageAlt": "B3 balance charger"
      },
      {
        "id": "77",
        "label": "10 W",
        "name": "B3 10W Balance Charger",
        "model": "B3 10W",
        "price": "HK$52",
        "tier1Price": "HK$52",
        "image": "/manus-storage/excel_prod_4_5d33c966.png",
        "imageAlt": "B3 10W balance charger"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "tops-shield-200",
    "order": 11,
    "visible": true,
    "title": {
      "en": "TOPS Shield 200 Brushless",
      "zh-Hant": "TOPS 飛盾 200 無刷版"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "2026 New Brushless Drone Highlights: This 200mm brushless soccer drone delivers ultimate cost-performance. Equipped with high-performance brushless motors, it achieves 90% performance of similar open-source brushless products on the market at only one-third the price. Perfect for hollow-cup pilots upgrading to brushless training. Features dual carbon fiber plates to minimize damage during daily practice and substantially reduce maintenance costs.",
      "zh-Hant": "2026新款無刷無人機特色亮點：此款200mm無刷足球無人機，打造極致性價比，搭載高性能無刷電機對比市面上同類開源無刷產品，性能可達到其90%，價格只有其三分之一，可充分滿足空心杯進階選手的訓練需求，且採用雙碳板設計可以在日常訓練中減少配件的損壞解決了無刷訓練成本高的問題。"
    },
    "variants": [
      {
        "id": "5",
        "label": "Standard",
        "name": "TOPS Shield 200 Brushless",
        "model": "200 mm brushless",
        "price": "HK$1,200",
        "tier1Price": "HK$1,200",
        "image": "/media/Droneequipment_2ab6c2b7.jpg",
        "imageAlt": "TOPS Shield 200 brushless competition drone"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Dimensions",
            "200*200*180mm"
          ],
          [
            "Receiver Mode",
            "Built-in or external"
          ],
          [
            "Control Radius",
            "< 100 m"
          ],
          [
            "Recommended Battery",
            "3S 650mAh - 3S 950mAh"
          ],
          [
            "Motor",
            "1505 4000KV"
          ],
          [
            "ESC",
            "25A 4-in-1 open-source ESC"
          ],
          [
            "Flight Controller",
            "GT02 closed-source FC"
          ],
          [
            "Flight Time",
            "4-6 mins"
          ],
          [
            "Lighting",
            "Dual-channel lighting interface"
          ],
          [
            "Colour Options",
            "Red, Blue, White"
          ]
        ],
        "inTheBox": [
          "1x Drone soccer aircraft",
          "1x 3S battery",
          "1x Remote controller",
          "1x Charger",
          "1x Accessory pack",
          "1x Packaging box"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "外形尺寸",
            "200*200*180"
          ],
          [
            "接收機模式",
            "內置或外接"
          ],
          [
            "操控半徑",
            "小於100米"
          ],
          [
            "推薦電池",
            "3S650-3S950"
          ],
          [
            "電機",
            "1505 4000KV"
          ],
          [
            "電調",
            "25A4合一開源電調"
          ],
          [
            "飛控",
            "GT02閉源飛控"
          ],
          [
            "續航時間",
            "4-6分鐘"
          ],
          [
            "燈光",
            "兩路燈光接口"
          ],
          [
            "顏色",
            "紅色、藍色、白色"
          ]
        ],
        "inTheBox": [
          "1x 足球無人機",
          "1x 3S電池",
          "1x 遙控器",
          "1x 充電器",
          "1x 配件包",
          "1x 包裝盒"
        ]
      }
    }
  },
  {
    "familyId": "d6-pro",
    "order": 12,
    "visible": true,
    "title": {
      "en": "D6 PRO Smart Charger",
      "zh-Hant": "D6 PRO 智能充電器"
    },
    "category": {
      "en": "Charging equipment",
      "zh-Hant": "充電設備"
    },
    "description": {
      "en": "Charges 1S-6S batteries. Each set includes 2x XT60 to XT30 adapters.",
      "zh-Hant": "可充1S-6S電池，每套配2個XT60轉XT30轉接頭。"
    },
    "variants": [
      {
        "id": "78",
        "label": "Dual-channel",
        "name": "D6 PRO Smart Charger",
        "model": "D6 PRO",
        "price": "HK$874.80",
        "tier1Price": "HK$874.80",
        "image": "/manus-storage/excel_prod_25_422ab006.png",
        "imageAlt": "D6 PRO smart balance charger"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Input Voltage",
            "AC 100~240V / DC 6.5~30V"
          ],
          [
            "Charge Current",
            "0.1~15A x 2"
          ],
          [
            "Charge Power",
            "DC 325W x 2 (650W) / AC 200W (supports power distribution)"
          ],
          [
            "Discharge Power",
            "Internal 15W x 2 (balance port 10W) / External 325W x 2 (650W)"
          ],
          [
            "Battery Types",
            "LiHv/LiPo/LiFe/Lilon/Lixx: 1~6S; NiZn/Nicd/NiMH: 1~16S; Smart Battery: 1~6S; Lead Acid (Pb): 2~24V; Eneloop: 1~16S"
          ],
          [
            "Balance Current",
            "1600mA x 2"
          ],
          [
            "Discharge Current",
            "0.1~3A x 2 / External Discharge: 1~15A x 2"
          ],
          [
            "USB Output",
            "5V / 2.1A"
          ],
          [
            "Dimensions",
            "108x105x76mm"
          ],
          [
            "Net Weight",
            "555g"
          ]
        ],
        "inTheBox": [
          "1x D6 PRO Smart Balance Charger",
          "2x XT60 to XT30 Adapter"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "輸入電壓",
            "AC 100~240V/DC 6.5~30V"
          ],
          [
            "充電電流",
            "0.1~15Ax2"
          ],
          [
            "充電功率",
            "DC 325W x 2（650W） / AC 200W（支持配電）"
          ],
          [
            "放電功率內部放電",
            "15W x 2（平衡端口10W）"
          ],
          [
            "外部放電",
            "325W x2（650W）"
          ],
          [
            "電池類型",
            "LiHvLiPo/LiFe/Lilon/Lixx: 1~6S; NiZn/Nicd/NiMH: 1~16S; 智慧電池: 1~6S; 鉛酸(Pb): 2~24V; Eneloop: 1~16S"
          ],
          [
            "平衡電流",
            "1600mAx2"
          ],
          [
            "放電電流",
            "0.1~3Ax2"
          ],
          [
            "外部放電電流",
            "1~15Ax2"
          ],
          [
            "USB輸出",
            "5V/2.1A"
          ],
          [
            "尺寸",
            "108x105x76毫米"
          ],
          [
            "淨重",
            "555克"
          ]
        ],
        "inTheBox": [
          "1x D6 PRO智能平衡充電器",
          "2x XT60轉XT30轉接頭"
        ]
      }
    }
  },
  {
    "familyId": "tops-shield-200-cup",
    "order": 12,
    "visible": true,
    "title": {
      "en": "TOPS Shield 200 Brushed RTF Set",
      "zh-Hant": "TOPS 飛盾 200 空心杯足球無人機套裝"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "Purpose-built for competitions, compliant with ASFC F9A-B competition standards. Multiple mode switching: one-key takeoff/landing, 360° flips, 3-speed rates, auto-leveling, position hold, auto-roll, etc. Fully compliant with national and international drone soccer tournaments (e.g., Feibei National Competition, Golden Key Provincial Competition, World Drone Soccer Championship). Also ideal for STEM classes and pre-competition training. Features an ultra-flexible crash-resistant safety cage for maximum durability and safety among peers. Whitelisted tournament competition equipment.",
      "zh-Hant": "專為競賽設計，符合ASFC F9A-B競賽標準。多種模式隨意切換，一鍵起飛降落、360度翻轉、三擋調速、自動穩定飛行、實現定點飛行、一鍵翻滾等。飛盾足球無人機參數符合各類空中足球無人機競賽項目，如飛北全國性競賽、金鑰匙省級競賽以及國際競賽等。同時也適合學生平時上課練習和賽前集訓。外殼採用柔韌安全殼，防碎防撞，集參賽、學習、玩樂於一體。在同類型產品中安全係數最高。白名單賽事用比賽器材。"
    },
    "variants": [
      {
        "id": "19",
        "label": "Portable RTF set",
        "name": "TOPS Shield 200 Brushed RTF Set",
        "model": "TZ001",
        "price": "HK$810",
        "tier1Price": "HK$810",
        "image": "/media/Droneequipment_2ab6c2b7.jpg",
        "imageAlt": "TOPS Shield 200 portable ready-to-fly drone set"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Dimensions",
            "200*200*180mm"
          ],
          [
            "Wheelbase",
            "115mm"
          ],
          [
            "Propeller Diameter",
            "66mm"
          ],
          [
            "Standard Battery",
            "2S 450mAh 7.4V 42*25*10mm JST connector LiPo"
          ],
          [
            "Flight Modes",
            "Altitude hold, Self-leveling, Headless mode, 3-speed rates"
          ],
          [
            "LED",
            "Front/rear LED indicators with 7-color transition"
          ],
          [
            "Communication",
            "2.4G wireless RF"
          ],
          [
            "Body Weight",
            "75g (dry) / 100g (with battery)"
          ],
          [
            "Standard Takeoff Weight",
            "99g"
          ],
          [
            "Max Takeoff Weight",
            "<100g"
          ],
          [
            "Max Flight Time",
            ">5 mins"
          ],
          [
            "Control Radius",
            "<100m"
          ],
          [
            "Battery Config",
            "2x 2S batteries + 4x AAA controller batteries included"
          ],
          [
            "OEM",
            "Customization supported"
          ],
          [
            "Box Dimensions",
            "32*23.5*21.5cm"
          ],
          [
            "Colour Options",
            "Red, Blue, White"
          ]
        ],
        "inTheBox": [
          "1x Drone soccer aircraft",
          "2x 2S battery",
          "1x Remote controller",
          "1x User manual",
          "4x AAA battery",
          "1x Accessory pack",
          "1x Gift box packaging"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "外形尺寸",
            "200*200*180mm"
          ],
          [
            "飛機軸距",
            "115mm"
          ],
          [
            "槳葉直徑",
            "66mm"
          ],
          [
            "標配電池",
            "2S 450mah 7.4V 42*25*10 JST接頭 鋰電池"
          ],
          [
            "模式切換",
            "定高、自穩、無頭模式、三段變速"
          ],
          [
            "LED燈",
            "前後LED指示燈，燈光七色變化"
          ],
          [
            "通信方式",
            "2.4G無線高頻信號"
          ],
          [
            "機身重量",
            "空機75g 含電池100g"
          ],
          [
            "標準起飛重量",
            "99克"
          ],
          [
            "最大起飛重量",
            "<100克"
          ],
          [
            "最大飛行時間",
            ">5分鐘"
          ],
          [
            "飛行控制半徑",
            "<100米"
          ],
          [
            "電池配置",
            "每套含配2S電池2塊、遙控器7號乾電池4個"
          ],
          [
            "OEM",
            "可接受OEM定制"
          ],
          [
            "彩盒尺寸",
            "32*23.5*21.5cm"
          ],
          [
            "顏色",
            "紅、藍、白可選"
          ]
        ],
        "inTheBox": [
          "1x 足球無人機",
          "2x 2S電池",
          "1x 遙控器",
          "1x 說明書",
          "4x 7號乾電池",
          "1x 配件包",
          "1x 禮盒包裝"
        ]
      }
    }
  },
  {
    "familyId": "inflatable-drone-soccer-field",
    "order": 13,
    "visible": false,
    "title": {
      "en": "Inflatable Drone Soccer Field",
      "zh-Hant": "充氣式無人機足球場"
    },
    "category": {
      "en": "Competition venue",
      "zh-Hant": "比賽場地"
    },
    "description": {
      "en": "Inflatable drone soccer field options with goals and pump.",
      "zh-Hant": "配備球門及氣泵的充氣式無人機足球場選項。"
    },
    "variants": [
      {
        "id": "91",
        "label": "3 × 3 × 3 m",
        "name": "Inflatable Drone Soccer Field 3 × 3 × 3 m",
        "model": "3 × 3 × 3 m",
        "price": "HK$5,733",
        "tier1Price": "HK$5,733",
        "image": "/manus-storage/excel_prod_7_7475981f.png",
        "imageAlt": "Inflatable drone soccer field with two goals"
      },
      {
        "id": "94",
        "label": "6 × 3 × 3 m",
        "name": "Inflatable Drone Soccer Field 6 × 3 × 3 m",
        "model": "6 × 3 × 3 m",
        "price": "HK$7,813",
        "tier1Price": "HK$7,813",
        "image": "/manus-storage/excel_prod_8_903cb396.png",
        "imageAlt": "Large inflatable drone soccer field with two goals"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "tops-shield-200-battery",
    "order": 13,
    "visible": true,
    "title": {
      "en": "TOPS Shield 200 2S Battery",
      "zh-Hant": "TOPS 飛盾 200 2S 電池"
    },
    "category": {
      "en": "Drone power",
      "zh-Hant": "無人機電源"
    },
    "description": {
      "en": "Dedicated drone soccer battery, compatible with Flying Shield & Feiying series.",
      "zh-Hant": "足球無人機專用電池，飛盾飛影通用款。"
    },
    "variants": [
      {
        "id": "20",
        "label": "450 mAh · 2S",
        "name": "TOPS Shield 200 450 mAh 2S Battery",
        "model": "2S 7.4 V 25C",
        "price": "HK$35",
        "tier1Price": "HK$35",
        "image": "/media/Droneequipment_2ab6c2b7.jpg",
        "imageAlt": "TOPS Shield 200 2S flight battery"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Product",
            "Model Aviation Power LiPo Battery"
          ],
          [
            "Material",
            "Lithium Cobalt Oxide (LiCoO2)"
          ],
          [
            "Nominal Voltage",
            "7.4V"
          ],
          [
            "Charge Voltage",
            "7.4V"
          ],
          [
            "Charge Current/Input",
            "5V, 1A, 2A"
          ],
          [
            "Discharge Rate",
            "25C"
          ],
          [
            "Storage Temperature",
            "25±5°C / -1±5°C"
          ],
          [
            "Storage Voltage",
            "7.6V"
          ],
          [
            "Storage Condition",
            "Keep away from direct sunlight & moisture"
          ],
          [
            "Compatibility",
            "Drone soccer, multirotors, RC airplanes, helicopters, RC cars, etc."
          ],
          [
            "Package Dimensions",
            "5.5*2.5*0.8cm"
          ]
        ],
        "inTheBox": [
          "1x 450mAh 2S battery"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "產品名稱",
            "航模動力鋰電池"
          ],
          [
            "電池材質",
            "鈷酸鋰"
          ],
          [
            "標準電壓",
            "7.4V"
          ],
          [
            "充電電壓",
            "7.4V"
          ],
          [
            "充電電壓/電流",
            "5V、1A、2A"
          ],
          [
            "放電倍率",
            "25C"
          ],
          [
            "實際儲存溫度",
            "25±5℃/-1±5℃"
          ],
          [
            "儲存電壓",
            "7.6V"
          ],
          [
            "儲存環境",
            "避免陽光直射、避免受潮"
          ],
          [
            "適用範圍",
            "航模無人機、多軸飛行器、遙控飛機、直升機、小汽車等"
          ],
          [
            "包裝尺寸",
            "5.5*2.5*0.8cm"
          ]
        ],
        "inTheBox": [
          "1x 450mah 2S電池"
        ]
      }
    }
  },
  {
    "familyId": "gmb-4s-battery",
    "order": 14,
    "visible": true,
    "title": {
      "en": "GMB High-Energy 4S Battery",
      "zh-Hant": "GMB 高能 4S 電池"
    },
    "category": {
      "en": "Drone power",
      "zh-Hant": "無人機電源"
    },
    "description": {
      "en": "For brushless FPV racing drones and brushless soccer drones.",
      "zh-Hant": "無刷穿越機、無刷球機用。"
    },
    "variants": [
      {
        "id": "72",
        "label": "3000 mAh · 4S",
        "name": "GMB High-Energy 15.2 V 3000 mAh 4S Battery",
        "model": "4S 15.2 V",
        "price": "HK$288",
        "tier1Price": "HK$288",
        "image": "/media/Droneequipment_2ab6c2b7.jpg",
        "imageAlt": "GMB high-energy 4S drone battery"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Voltage",
            "15.2V"
          ],
          [
            "Capacity",
            "3000mAh 4S"
          ],
          [
            "Connector",
            "120C XT60 discharge connector"
          ]
        ],
        "inTheBox": [
          "1x 15.2V 3000mAh 4S battery"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "電壓",
            "15.2V"
          ],
          [
            "容量",
            "3000mAh 4S"
          ],
          [
            "放電接頭",
            "120C XT60放電接頭"
          ]
        ],
        "inTheBox": [
          "1x 15.2V 3000mAh 4S電池"
        ]
      }
    }
  },
  {
    "familyId": "ta300-charger",
    "order": 15,
    "visible": true,
    "title": {
      "en": "TA300 300W Eight-Channel Charger",
      "zh-Hant": "TA300 300W 八通道充電器"
    },
    "category": {
      "en": "Charging equipment",
      "zh-Hant": "充電設備"
    },
    "description": {
      "en": "Equipped with 8 independent channels, real-time battery monitoring, plug-and-charge convenience, and 8-fold safety protection, balancing high efficiency and reliability.",
      "zh-Hant": "配備8個獨立通道、實時電池監控、即插即充、八重安全防護，兼顧高效與可靠。"
    },
    "variants": [
      {
        "id": "79",
        "label": "Eight-channel",
        "name": "TA300 300W Eight-Channel 2–4S Smart Charger",
        "model": "TA300",
        "price": "HK$958.80",
        "tier1Price": "HK$958.80",
        "image": "/media/Droneequipment_2ab6c2b7.jpg",
        "imageAlt": "TA300 eight-channel smart battery charger"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Input Voltage",
            "AC 100V-240V"
          ],
          [
            "Total Output Power",
            "300W"
          ],
          [
            "Total Discharge Power",
            "3W x 8"
          ],
          [
            "Max Charge Current",
            "2A"
          ],
          [
            "Supported Batteries",
            "LiPo / LiHV / LiFe / Li-ion"
          ],
          [
            "Cell Count",
            "2-4S"
          ],
          [
            "Functions",
            "Charge, Storage"
          ],
          [
            "Dimensions",
            "161.3x95x58.7mm"
          ],
          [
            "Weight",
            "550g"
          ]
        ],
        "inTheBox": [
          "1x TATTU TA300 8-Channel Smart Charger"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "輸入電壓",
            "AC 100V-240V"
          ],
          [
            "總輸出功率",
            "300W"
          ],
          [
            "總放電功率",
            "3WX8"
          ],
          [
            "最大充電電流",
            "2A"
          ],
          [
            "充電電池類型",
            "LiPo/LiHV/LiFe/Li-lon"
          ],
          [
            "電池串數",
            "2-4S"
          ],
          [
            "功能",
            "充電、存儲"
          ],
          [
            "尺寸",
            "161.3x95x58.7mm"
          ],
          [
            "重量",
            "550g"
          ]
        ],
        "inTheBox": [
          "1x TATTU TA300八通道智能充電器"
        ]
      }
    }
  },
  {
    "familyId": "tops-bag-200",
    "order": 16,
    "visible": true,
    "title": {
      "en": "TOPS 200 mm Drone Carry Bag",
      "zh-Hant": "TOPS 200 毫米球機收納包"
    },
    "category": {
      "en": "Event equipment",
      "zh-Hant": "賽事設備"
    },
    "description": {
      "en": "Aircraft storage bag, 200mm sphere soccer drone competition outdoor portable carry case.",
      "zh-Hant": "飛行器收納包，200球形無人機競賽戶外便攜無人機包。"
    },
    "variants": [
      {
        "id": "83",
        "label": "200 mm",
        "name": "TOPS Drone Carry Bag for 200 mm Ball Drone",
        "model": "200 mm",
        "price": "HK$180",
        "tier1Price": "HK$180",
        "image": "/media/Droneequipment_2ab6c2b7.jpg",
        "imageAlt": "TOPS carry bag for a 200 mm drone"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Weight",
            "1234g"
          ],
          [
            "External Dimensions",
            "373*222*223mm"
          ]
        ],
        "inTheBox": [
          "1x Storage bag",
          "1x Shoulder strap"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "重量",
            "1234g"
          ],
          [
            "外尺寸",
            "373*222*223mm"
          ]
        ],
        "inTheBox": [
          "1x 收納包",
          "1x 掛帶"
        ]
      }
    }
  },
  {
    "familyId": "tops-bag-220",
    "order": 17,
    "visible": true,
    "title": {
      "en": "TOPS 200–220 mm Drone Carry Bag",
      "zh-Hant": "TOPS 200–220 毫米球機收納包"
    },
    "category": {
      "en": "Event equipment",
      "zh-Hant": "賽事設備"
    },
    "description": {
      "en": "Aircraft storage bag, 200-220mm diameter sphere soccer drone competition outdoor portable carry case (universal model).",
      "zh-Hant": "飛行器收納包，200-220直徑球形無人機競賽戶外便攜無人機包（通用款）。"
    },
    "variants": [
      {
        "id": "84",
        "label": "200–220 mm",
        "name": "TOPS Drone Carry Bag for 200–220 mm Ball Drone",
        "model": "200–220 mm",
        "price": "HK$264",
        "tier1Price": "HK$264",
        "image": "/media/Droneequipment_2ab6c2b7.jpg",
        "imageAlt": "TOPS carry bag for a 200 to 220 mm drone"
      }
    ],
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "Technical Specifications",
        "inTheBoxTitle": "What's in the Box",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "Weight",
            "1220g"
          ],
          [
            "External Dimensions",
            "376*200*210mm"
          ]
        ],
        "inTheBox": [
          "1x Storage bag",
          "1x Shoulder strap"
        ]
      },
      "zh-Hant": {
        "platformLabel": "",
        "premiumTitle": "",
        "careTitle": "",
        "careDescription": "",
        "specificationsTitle": "技術規格",
        "inTheBoxTitle": "包裝內容",
        "equipmentTierPartsLabel": "",
        "equipmentTierPartsDescription": "",
        "equipmentTierVerifiedLabel": "",
        "equipmentTierVerifiedDescription": "",
        "careAddOnTitle": "",
        "careAddOnDescription": "",
        "tiers": {},
        "specifications": [
          [
            "重量",
            "1220g"
          ],
          [
            "外尺寸",
            "376*200*210mm"
          ]
        ],
        "inTheBox": [
          "1x 收納包",
          "1x 掛帶"
        ]
      }
    }
  }
];
