// Generated by scripts/generate-product-data.mts. Edit Markdown files under content/products instead.
export type ProductVariantContentRecord = {
  id: string;
  label: string;
  name: string;
  model: string;
  price: string;
  tier?: string;
  image: string;
  imageAlt: string;
};
export type ProductDetailContentRecord = {
  familyId: string;
  order: number;
  visible: boolean;
  title: { en: string; "zh-Hant": string };
  category: { en: string; "zh-Hant": string };
  description: { en: string; "zh-Hant": string };
  variants: ProductVariantContentRecord[];
  defaultTier?: string;
  vliCareTiers: string[];
  detail?: {
    en: { platformLabel: string; premiumTitle: string; careTitle: string; careDescription: string; tiers: Record<string, { label: string; subtitle: string; features: string[] }>; specifications: Array<[string, string]>; inTheBox: string[] };
    "zh-Hant": { platformLabel: string; premiumTitle: string; careTitle: string; careDescription: string; tiers: Record<string, { label: string; subtitle: string; features: string[] }>; specifications: Array<[string, string]>; inTheBox: string[] };
  };
};
export const productContent: readonly ProductDetailContentRecord[] = [
  {
    "familyId": "tops-shield-205",
    "order": 1,
    "visible": true,
    "title": {
      "en": "TOPS Shield 205",
      "zh-Hant": "TOPS Shield 205"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "Engineered for high-intensity drone sports, the TOPS Shield 205 combines a lightweight 205mm spherical exoskeleton with a competition-tuned powertrain. Designed to bounce off arena walls and opponents without dropping from the sky, it is the ultimate platform for tight-quarters maneuverability.",
      "zh-Hant": "TOPS Shield 205 專為高強度無人機運動而設，結合輕量化 205 毫米球形外骨骼與競賽調校動力系統。即使碰撞場地圍網或對手，也能保持飛行，是狹窄空間靈活操控的理想平台。"
    },
    "variants": [
      {
        "id": "25",
        "label": "RTF",
        "name": "TOPS Shield 205 RTF",
        "model": "TZ009",
        "price": "HK$4,329",
        "tier": "certified",
        "image": "/manus-storage/excel_prod_30_a7d07b66.png",
        "imageAlt": "TOPS Shield 205 competition drone kit box"
      },
      {
        "id": "26",
        "label": "PNP",
        "name": "TOPS Shield 205 PNP",
        "model": "TZ009",
        "price": "HK$2,743",
        "tier": "builder",
        "image": "/manus-storage/excel_prod_31_93c6811c.png",
        "imageAlt": "TOPS Shield 205 PNP competition drone product image"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "205 mm platform",
        "premiumTitle": "TOPS Shield 205: The Agile Striker",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "tiers": {
          "builder": {
            "label": "Builder's Edition",
            "subtitle": "For teams with in-house technicians.",
            "features": [
              "Factory default settings (requires manual PID tuning).",
              "Standard manufacturer visual inspection.",
              "Standard 14-day defect return policy (Does not cover flight crashes)."
            ]
          },
          "certified": {
            "label": "VLI Certified Edition",
            "subtitle": "Plug-and-play for professional arenas and schools.",
            "features": [
              "Professionally tuned by VLI engineers for arena agility.",
              "15-point VLI Pre-Flight Verification (motors and ESCs stress-tested).",
              "Includes 1-Year VLI CARE: Covers heavy collision damage, water damage, and rapid replacements."
            ]
          }
        },
        "specifications": [
          [
            "Frame Diameter",
            "205 mm"
          ],
          [
            "Design",
            "Spherical impact-resistant competition cage"
          ],
          [
            "Flight Dynamics",
            "360-degree collision tolerance with auto-righting"
          ],
          [
            "Propulsion",
            "High-torque brushless motors"
          ],
          [
            "Telemetry",
            "Low-latency transmission, fully compatible with Smart Referee systems"
          ]
        ],
        "inTheBox": [
          "1x TOPS Shield 205 Competition Ball Drone",
          "1x Pre-Bound Receiver / Transmission Unit",
          "2x Sets of Competition Propellers",
          "1x High-Impact Spare Outer Shell Segment",
          "1x Custom VLI Transport Bag"
        ]
      },
      "zh-Hant": {
        "platformLabel": "205 毫米平台",
        "premiumTitle": "TOPS Shield 205：靈活進攻平台",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "tiers": {
          "builder": {
            "label": "Builder’s Edition",
            "subtitle": "適合具備內部技術人員的隊伍。",
            "features": [
              "原廠預設設定（需要手動 PID 調校）。",
              "標準製造商目視檢查。",
              "標準 14 天產品缺陷退貨政策（不涵蓋飛行碰撞）。"
            ]
          },
          "certified": {
            "label": "VLI Certified Edition",
            "subtitle": "適合專業場地及學校的即插即用配置。",
            "features": [
              "由 VLI 工程師為場地靈活性進行專業調校。",
              "15 項 VLI 交付前檢查（馬達及 ESC 經壓力測試）。",
              "包括一年 VLI CARE：涵蓋嚴重碰撞損壞、進水損壞及快速更換。"
            ]
          }
        },
        "specifications": [
          [
            "機架直徑",
            "205 毫米"
          ],
          [
            "設計",
            "耐撞擊球形競賽保護架"
          ],
          [
            "飛行動態",
            "360 度碰撞容錯及自動翻正"
          ],
          [
            "推進系統",
            "高扭矩無刷馬達"
          ],
          [
            "遙測",
            "低延遲傳輸，完全兼容 Smart Referee 系統"
          ]
        ],
        "inTheBox": [
          "1x TOPS Shield 205 競賽球形無人機",
          "1x 已綁定接收器／傳輸單元",
          "2x 套競賽螺旋槳",
          "1x 高抗衝擊備用外殼組件",
          "1x VLI 專用運輸袋"
        ]
      }
    }
  },
  {
    "familyId": "tops-shield-220",
    "order": 2,
    "visible": true,
    "title": {
      "en": "TOPS Shield 220",
      "zh-Hant": "TOPS Shield 220"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "The TOPS Shield 220 gives competition teams a balanced 220mm platform for repeatable training and event deployment. Choose a ready-to-fly configuration for a faster operational start, add the travel set when logistics matter, or bring your own receiver for an in-house build workflow.",
      "zh-Hant": "TOPS Shield 220 為競賽隊伍提供平衡的 220 毫米平台，適合重複訓練及賽事部署。您可選擇開箱即飛配置以快速投入運作，在重視物流時加入運輸套裝，或使用自備接收器建立內部技術流程。"
    },
    "variants": [
      {
        "id": "27",
        "label": "RTF",
        "name": "TOPS Shield 220 RTF",
        "model": "TZ002",
        "price": "HK$3,718",
        "tier": "certified",
        "image": "/manus-storage/excel_prod_9_417b350f.png",
        "imageAlt": "TOPS Shield 220 competition drone cage illustration"
      },
      {
        "id": "28",
        "label": "RTF + Bag",
        "name": "TOPS Shield 220 RTF + Bag",
        "model": "TZ002",
        "price": "HK$4,056",
        "tier": "travel",
        "image": "/manus-storage/excel_prod_21_68f8cfe7.png",
        "imageAlt": "TOPS Shield 220 drone with remote controller"
      },
      {
        "id": "29",
        "label": "PNP",
        "name": "TOPS Shield 220 PNP",
        "model": "TZ002",
        "price": "HK$2,743",
        "tier": "builder",
        "image": "/manus-storage/excel_prod_24_65d1f683.png",
        "imageAlt": "TOPS Shield 220 PNP competition drone cage diagram"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "220 mm platform",
        "premiumTitle": "TOPS Shield 220: The Competition Workhorse",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "tiers": {
          "certified": {
            "label": "VLI Certified Edition",
            "subtitle": "Ready-to-fly for competition teams and schools.",
            "features": [
              "Competition-ready receiver and flight setup.",
              "VLI pre-flight configuration check before handover.",
              "Includes 1-Year VLI CARE for approved programme deployments."
            ]
          },
          "travel": {
            "label": "Certified Travel Edition",
            "subtitle": "Ready-to-fly with a transport bag for touring programmes.",
            "features": [
              "Ready-to-fly 220mm platform with matched flight electronics.",
              "Includes a carrying bag for training and event travel.",
              "Designed for teams moving equipment between venues."
            ]
          },
          "builder": {
            "label": "Builder's Edition",
            "subtitle": "PNP platform for teams with their own control system.",
            "features": [
              "Bring your own receiver and control equipment.",
              "Flexible starting point for technical teams and custom builds.",
              "Standard manufacturer inspection before dispatch."
            ]
          }
        },
        "specifications": [
          [
            "Frame Diameter",
            "220 mm"
          ],
          [
            "Configuration",
            "RTF, travel-ready, or PNP platform options"
          ],
          [
            "Use Case",
            "Training, competition, and touring event programmes"
          ],
          [
            "Flight Setup",
            "Competition-ready power and control configuration"
          ],
          [
            "Compatibility",
            "Suitable for Smart Referee-supported drone sports workflows"
          ]
        ],
        "inTheBox": [
          "1x TOPS Shield 220 Competition Ball Drone",
          "1x Receiver / Transmission Unit on RTF configurations",
          "2x Sets of Competition Propellers",
          "1x High-Impact Spare Outer Shell Segment",
          "1x Carrying Bag on Travel Edition"
        ]
      },
      "zh-Hant": {
        "platformLabel": "220 毫米平台",
        "premiumTitle": "TOPS Shield 220：競賽主力平台",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "tiers": {
          "certified": {
            "label": "VLI Certified Edition",
            "subtitle": "適合競賽隊伍及學校的開箱即飛配置。",
            "features": [
              "競賽就緒的接收器及飛行設定。",
              "交付前由 VLI 進行配置檢查。",
              "獲認可的計劃部署包括一年 VLI CARE。"
            ]
          },
          "travel": {
            "label": "Certified Travel Edition",
            "subtitle": "配備運輸袋，適合巡迴計劃的開箱即飛配置。",
            "features": [
              "配備匹配飛行電子設備的 220 毫米開箱即飛平台。",
              "包括訓練及賽事運輸用攜行袋。",
              "適合在不同場地之間運送設備的隊伍。"
            ]
          },
          "builder": {
            "label": "Builder’s Edition",
            "subtitle": "適合使用自備控制系統的隊伍的 PNP 平台。",
            "features": [
              "使用自備接收器及控制設備。",
              "為技術隊伍及客製化組裝提供靈活起點。",
              "出貨前進行標準製造商檢查。"
            ]
          }
        },
        "specifications": [
          [
            "機架直徑",
            "220 毫米"
          ],
          [
            "配置",
            "RTF、旅行就緒或 PNP 平台選項"
          ],
          [
            "用途",
            "訓練、競賽及巡迴賽事計劃"
          ],
          [
            "飛行設定",
            "競賽就緒的電源及控制配置"
          ],
          [
            "兼容性",
            "適用於 Smart Referee 支援的無人機運動流程"
          ]
        ],
        "inTheBox": [
          "1x TOPS Shield 220 競賽球形無人機",
          "1x RTF 配置接收器／傳輸單元",
          "2x 套競賽螺旋槳",
          "1x 高抗衝擊備用外殼組件",
          "1x Travel Edition 攜行袋"
        ]
      }
    }
  },
  {
    "familyId": "fb200-racer",
    "order": 3,
    "visible": false,
    "title": {
      "en": "FB200 Racer",
      "zh-Hant": "FB200 Racer"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "200 mm ready-to-fly racer with ball guard and essential flying kit.",
      "zh-Hant": "200 毫米開箱即飛競速機，配備球形保護架及基本飛行套裝。"
    },
    "variants": [
      {
        "id": "30",
        "label": "RTF",
        "name": "FB200 RTF Racer",
        "model": "FB200",
        "price": "HK$5,252",
        "image": "/manus-storage/excel_prod_10_e5fc5653.png",
        "imageAlt": "FB200 RTF racer drone with remote controller"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "fb210-racer",
    "order": 4,
    "visible": false,
    "title": {
      "en": "FB210 Racer",
      "zh-Hant": "FB210 Racer"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "210 mm ready-to-fly ball drone with upgraded motor package and carry bag.",
      "zh-Hant": "210 毫米開箱即飛球形無人機，配備升級馬達套裝及攜行袋。"
    },
    "variants": [
      {
        "id": "31",
        "label": "RTF",
        "name": "FB210 RTF Racer",
        "model": "FB210",
        "price": "HK$5,993",
        "image": "/manus-storage/excel_prod_11_fc95565c.png",
        "imageAlt": "FB210 RTF racer drone with remote controller"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "r200",
    "order": 5,
    "visible": false,
    "title": {
      "en": "R200",
      "zh-Hant": "R200"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "Compact 200 mm ball drone platform with 3S power setup.",
      "zh-Hant": "配備 3S 電源配置的緊湊型 200 毫米球形無人機平台。"
    },
    "variants": [
      {
        "id": "32",
        "label": "RTF",
        "name": "R200 RTF",
        "model": "R200",
        "price": "HK$5,590",
        "image": "/manus-storage/excel_prod_13_712f9740.png",
        "imageAlt": "R200 RTF competition drone with remote controller"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "r200f",
    "order": 6,
    "visible": false,
    "title": {
      "en": "R200F",
      "zh-Hant": "R200F"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "Higher-output 200 mm ball drone platform with 3S–4S capability.",
      "zh-Hant": "支援 3S 至 4S、輸出更高的 200 毫米球形無人機平台。"
    },
    "variants": [
      {
        "id": "33",
        "label": "RTF",
        "name": "R200F RTF",
        "model": "R200F",
        "price": "HK$5,616",
        "image": "/manus-storage/excel_prod_15_cb880557.png",
        "imageAlt": "R200F RTF competition drone with remote controller"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "r220f",
    "order": 7,
    "visible": true,
    "title": {
      "en": "R220F",
      "zh-Hant": "R220F"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "The R220F is a practical 220mm ball-drone platform for organisations that need a complete, portable setup. Its upgraded motor, battery, and carrying bag make it a straightforward choice for training fleets, demonstrations, and event-side replacement capacity.",
      "zh-Hant": "R220F 是一款實用的 220 毫米球形無人機平台，適合需要完整便攜配置的機構。升級馬達、電池及攜行袋讓它成為訓練機隊、示範活動及賽事備用機的直接選擇。"
    },
    "variants": [
      {
        "id": "34",
        "label": "RTF",
        "name": "R220F RTF",
        "model": "R220F",
        "price": "HK$5,993",
        "tier": "certified",
        "image": "/manus-storage/excel_prod_17_584dbd72.png",
        "imageAlt": "R220F RTF competition drone with remote controller"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [],
    "detail": {
      "en": {
        "platformLabel": "R220F platform",
        "premiumTitle": "R220F: The Ready-to-Deploy Training Platform",
        "careTitle": "VLI CARE not included",
        "careDescription": "This package does not include VLI CARE.",
        "tiers": {
          "certified": {
            "label": "VLI Ready-to-Deploy Edition",
            "subtitle": "Complete RTF setup for training, demonstration, and event support.",
            "features": [
              "Upgraded motor and matched flight battery included.",
              "Ready-to-fly configuration for faster programme setup.",
              "Includes a carrying bag for practical transport between venues."
            ]
          }
        },
        "specifications": [
          [
            "Frame Diameter",
            "220 mm"
          ],
          [
            "Configuration",
            "Ready-to-fly ball drone platform"
          ],
          [
            "Powertrain",
            "Upgraded motor with matched flight battery"
          ],
          [
            "Deployment",
            "Portable setup for training, demonstration, and event support"
          ],
          [
            "Transport",
            "Carrying bag included"
          ]
        ],
        "inTheBox": [
          "1x R220F Ready-to-Fly Ball Drone",
          "1x Upgraded Motor Configuration",
          "1x Matched Flight Battery",
          "1x Remote / Control Setup",
          "1x Carrying Bag"
        ]
      },
      "zh-Hant": {
        "platformLabel": "R220F 平台",
        "premiumTitle": "R220F：即時部署訓練平台",
        "careTitle": "不包括 VLI CARE",
        "careDescription": "此配置不包括 VLI CARE。",
        "tiers": {
          "certified": {
            "label": "VLI Ready-to-Deploy Edition",
            "subtitle": "適合訓練、示範及賽事支援的完整 RTF 配置。",
            "features": [
              "包括升級馬達及匹配飛行電池。",
              "開箱即飛配置，讓計劃更快投入運作。",
              "包括適合在不同場地之間運輸的攜行袋。"
            ]
          }
        },
        "specifications": [
          [
            "機架直徑",
            "220 毫米"
          ],
          [
            "配置",
            "開箱即飛球形無人機平台"
          ],
          [
            "動力系統",
            "升級馬達及匹配飛行電池"
          ],
          [
            "部署",
            "適合訓練、示範及賽事支援的便攜配置"
          ],
          [
            "運輸",
            "包括攜行袋"
          ]
        ],
        "inTheBox": [
          "1x R220F 開箱即飛球形無人機",
          "1x 升級馬達配置",
          "1x 匹配飛行電池",
          "1x 遙控／控制設定",
          "1x 攜行袋"
        ]
      }
    }
  },
  {
    "familyId": "tops-shield-400",
    "order": 8,
    "visible": true,
    "title": {
      "en": "TOPS Shield 400",
      "zh-Hant": "TOPS Shield 400"
    },
    "category": {
      "en": "Drone platform",
      "zh-Hant": "無人機平台"
    },
    "description": {
      "en": "The TOPS Shield 400 is built for larger-format drone sports where teams need more physical presence and endurance at the arena boundary. Select a ready-to-fly system for a complete deployment package or use the PNP platform as the foundation for your own receiver and battery workflow.",
      "zh-Hant": "TOPS Shield 400 為較大規模的無人機運動而設，適合隊伍在場館邊界需要更大體量及耐用性的情況。您可選擇完整部署套裝的開箱即飛系統，或以 PNP 平台作為自備接收器及電池流程的基礎。"
    },
    "variants": [
      {
        "id": "35",
        "label": "RTF",
        "name": "TOPS Shield 400 RTF",
        "model": "TZ003",
        "price": "HK$6,708",
        "tier": "certified",
        "image": "/manus-storage/excel_prod_26_26e91f83.png",
        "imageAlt": "TOPS Shield 400 competition drone in a blue cage"
      },
      {
        "id": "36",
        "label": "PNP",
        "name": "TOPS Shield 400 PNP",
        "model": "TZ003",
        "price": "HK$5,395",
        "tier": "builder",
        "image": "/manus-storage/excel_prod_19_2844a82e.png",
        "imageAlt": "TOPS Shield 400 PNP competition drone"
      }
    ],
    "defaultTier": "certified",
    "vliCareTiers": [
      "certified"
    ],
    "detail": {
      "en": {
        "platformLabel": "400 mm platform",
        "premiumTitle": "TOPS Shield 400: The Arena-Scale Platform",
        "careTitle": "Includes 1-Year VLI CARE",
        "careDescription": "Coverage for heavy collision damage, water damage, and rapid replacements.",
        "tiers": {
          "certified": {
            "label": "VLI Certified Arena Edition",
            "subtitle": "Ready-to-fly for larger-format matches and venue deployments.",
            "features": [
              "Complete flight-electronics configuration for arena-scale use.",
              "VLI pre-flight configuration check before handover.",
              "Designed for larger-format match operations and venue planning."
            ]
          },
          "builder": {
            "label": "Arena Builder's Edition",
            "subtitle": "PNP platform for technical teams with their own electronics.",
            "features": [
              "Bring your own receiver and battery workflow.",
              "Flexible foundation for venue-specific configuration.",
              "Standard manufacturer inspection before dispatch."
            ]
          }
        },
        "specifications": [
          [
            "Frame Diameter",
            "400 mm"
          ],
          [
            "Design",
            "Large-format spherical competition cage"
          ],
          [
            "Use Case",
            "Arena-scale matches and boundary operations"
          ],
          [
            "Configuration",
            "RTF or PNP platform options"
          ],
          [
            "Programme Fit",
            "Suitable for larger venues and higher-visibility deployments"
          ]
        ],
        "inTheBox": [
          "1x TOPS Shield 400 Competition Ball Drone",
          "1x Flight-Electronics Configuration on RTF Edition",
          "2x Sets of Competition Propellers",
          "1x High-Impact Outer Shell Component",
          "1x VLI Configuration Handover Checklist"
        ]
      },
      "zh-Hant": {
        "platformLabel": "400 毫米平台",
        "premiumTitle": "TOPS Shield 400：場館級平台",
        "careTitle": "包括一年 VLI CARE",
        "careDescription": "涵蓋嚴重碰撞損壞、進水損壞及快速更換支援。",
        "tiers": {
          "certified": {
            "label": "VLI Certified Arena Edition",
            "subtitle": "適合較大規模賽事及場館部署的開箱即飛配置。",
            "features": [
              "完整的場館級飛行電子設備配置。",
              "交付前由 VLI 進行配置檢查。",
              "為較大規模賽事運作及場館規劃而設。"
            ]
          },
          "builder": {
            "label": "Arena Builder’s Edition",
            "subtitle": "適合使用自備電子設備的技術隊伍的 PNP 平台。",
            "features": [
              "使用自備接收器及電池流程。",
              "為場館特定配置提供靈活基礎。",
              "出貨前進行標準製造商檢查。"
            ]
          }
        },
        "specifications": [
          [
            "機架直徑",
            "400 毫米"
          ],
          [
            "設計",
            "大型球形競賽保護架"
          ],
          [
            "用途",
            "場館級賽事及邊界運作"
          ],
          [
            "配置",
            "RTF 或 PNP 平台選項"
          ],
          [
            "計劃適配",
            "適合較大型場地及高可見度部署"
          ]
        ],
        "inTheBox": [
          "1x TOPS Shield 400 競賽球形無人機",
          "1x RTF Edition 飛行電子設備配置",
          "2x 套競賽螺旋槳",
          "1x 高抗衝擊外殼組件",
          "1x VLI 配置交付清單"
        ]
      }
    }
  },
  {
    "familyId": "ace-lipo-battery",
    "order": 9,
    "visible": false,
    "title": {
      "en": "ACE LiPo Battery",
      "zh-Hant": "ACE LiPo 電池"
    },
    "category": {
      "en": "Drone power",
      "zh-Hant": "無人機電源"
    },
    "description": {
      "en": "LiPo battery options for 200 mm, 220 mm, and higher-voltage 400 mm builds.",
      "zh-Hant": "適用於 200 毫米、220 毫米及高電壓 400 毫米配置的 LiPo 電池選項。"
    },
    "variants": [
      {
        "id": "69",
        "label": "3S · 1100 mAh",
        "name": "ACE 3S 1100 mAh Battery",
        "model": "3S battery",
        "price": "HK$234",
        "image": "/manus-storage/excel_prod_3_aa72f902.png",
        "imageAlt": "ACE 3S 1100 mAh LiPo battery"
      },
      {
        "id": "70",
        "label": "4S · 3000 mAh",
        "name": "ACE 4S 3000 mAh Battery",
        "model": "4S battery",
        "price": "HK$520",
        "image": "/manus-storage/excel_prod_27_854f107d.png",
        "imageAlt": "ACE 4S 3000 mAh LiPo battery"
      },
      {
        "id": "71",
        "label": "6S · 3000 mAh",
        "name": "ACE 6S 3000 mAh Battery",
        "model": "6S battery",
        "price": "HK$754",
        "image": "/manus-storage/excel_prod_28_5edbfa4d.png",
        "imageAlt": "ACE 6S 3000 mAh LiPo battery"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "usb-charger",
    "order": 10,
    "visible": false,
    "title": {
      "en": "10-Port USB Charger",
      "zh-Hant": "10 埠 USB 充電器"
    },
    "category": {
      "en": "Charging equipment",
      "zh-Hant": "充電設備"
    },
    "description": {
      "en": "Multi-port USB charger for compatible battery workflows.",
      "zh-Hant": "適用於兼容電池流程的多埠 USB 充電器。"
    },
    "variants": [
      {
        "id": "75",
        "label": "10-port",
        "name": "10-Port USB Charger",
        "model": "10-port USB charger",
        "price": "HK$117",
        "image": "/manus-storage/excel_prod_6_81781e24.png",
        "imageAlt": "10-port white USB charger"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "b3-balance-charger",
    "order": 11,
    "visible": false,
    "title": {
      "en": "B3 Balance Charger",
      "zh-Hant": "B3 平衡充電器"
    },
    "category": {
      "en": "Charging equipment",
      "zh-Hant": "充電設備"
    },
    "description": {
      "en": "Compact balance charger options for 2S and 3S LiPo batteries.",
      "zh-Hant": "適用於 2S 及 3S LiPo 電池的緊湊型平衡充電器選項。"
    },
    "variants": [
      {
        "id": "76",
        "label": "20 W",
        "name": "B3 20W Balance Charger",
        "model": "B3 20W",
        "price": "HK$65",
        "image": "/manus-storage/excel_prod_1_f4a517d6.png",
        "imageAlt": "B3 balance charger"
      },
      {
        "id": "77",
        "label": "10 W",
        "name": "B3 10W Balance Charger",
        "model": "B3 10W",
        "price": "HK$52",
        "image": "/manus-storage/excel_prod_4_5d33c966.png",
        "imageAlt": "B3 10W balance charger"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "d6-pro",
    "order": 12,
    "visible": true,
    "title": {
      "en": "D6 PRO Smart Charger",
      "zh-Hant": "D6 PRO 智能充電器"
    },
    "category": {
      "en": "Charging equipment",
      "zh-Hant": "充電設備"
    },
    "description": {
      "en": "Dual-channel smart balance charger for 1S–6S battery systems.",
      "zh-Hant": "適用於 1S 至 6S 電池系統的雙通道智能平衡充電器。"
    },
    "variants": [
      {
        "id": "78",
        "label": "Dual-channel",
        "name": "D6 PRO Smart Charger",
        "model": "D6 PRO",
        "price": "HK$1,365",
        "image": "/manus-storage/excel_prod_25_422ab006.png",
        "imageAlt": "D6 PRO smart balance charger"
      }
    ],
    "vliCareTiers": []
  },
  {
    "familyId": "inflatable-drone-soccer-field",
    "order": 13,
    "visible": false,
    "title": {
      "en": "Inflatable Drone Soccer Field",
      "zh-Hant": "充氣式無人機足球場"
    },
    "category": {
      "en": "Competition venue",
      "zh-Hant": "比賽場地"
    },
    "description": {
      "en": "Inflatable drone soccer field options with goals and pump.",
      "zh-Hant": "配備球門及氣泵的充氣式無人機足球場選項。"
    },
    "variants": [
      {
        "id": "91",
        "label": "3 × 3 × 3 m",
        "name": "Inflatable Drone Soccer Field 3 × 3 × 3 m",
        "model": "3 × 3 × 3 m",
        "price": "HK$5,733",
        "image": "/manus-storage/excel_prod_7_7475981f.png",
        "imageAlt": "Inflatable drone soccer field with two goals"
      },
      {
        "id": "94",
        "label": "6 × 3 × 3 m",
        "name": "Inflatable Drone Soccer Field 6 × 3 × 3 m",
        "model": "6 × 3 × 3 m",
        "price": "HK$7,813",
        "image": "/manus-storage/excel_prod_8_903cb396.png",
        "imageAlt": "Large inflatable drone soccer field with two goals"
      }
    ],
    "vliCareTiers": []
  }
];
