// Generated by scripts/generate-service-data.mts. Edit Markdown files under content/services instead.
export type ServiceContentRecord = {
  id: string;
  order: number;
  visible: boolean;
  icon: string;
  enquiryForm: "repair" | "general";
  title: { en: string; "zh-Hant": string };
  summary: { en: string; "zh-Hant": string };
  duration: { en: string; "zh-Hant": string };
  pricing: { en: string; "zh-Hant": string };
  image: string;
  imageAlt: { en: string; "zh-Hant": string };
  body: { en: string; "zh-Hant": string };
};
export const serviceContent: readonly ServiceContentRecord[] = [
  {
    "id": "drone-repair",
    "order": 1,
    "visible": true,
    "icon": "wrench",
    "enquiryForm": "repair",
    "title": {
      "en": "Drone Repair Service",
      "zh-Hant": "無人機維修服務"
    },
    "summary": {
      "en": "Mail in your drone for a repair assessment and quotation before any repair work begins, whether it needs diagnosis, component replacement, or rebuild support.",
      "zh-Hant": "寄送您的無人機進行維修評估與報價，於執行任何維修前先行評估——無論是故障診斷、零件更換或重建支援。"
    },
    "duration": {
      "en": "Mail-in assessment followed by quotation; repair timing depends on diagnosis and parts availability.",
      "zh-Hant": "先進行寄送評估並提供報價；維修時程視診斷結果與零件供應情況而定。"
    },
    "pricing": {
      "en": "Repair solution and quotation are provided first; delivery fees can be waived if the proposal is accepted and the repair is completed. Parts are separate.",
      "zh-Hant": "先提供維修方案與報價；若您接受提案並完成維修，運費可免。零件費用另計。"
    },
    "image": "/media/dronerepairthumb_ad988635.jpeg",
    "imageAlt": {
      "en": "Drone flight controller being inspected during a repair assessment",
      "zh-Hant": "維修評估期間正在檢查的無人機飛行控制器"
    },
    "body": {
      "en": "We will reply with mail-in instructions, assess the issue, and provide a repair solution and quotation before proceeding. Delivery fees can be waived if the proposed repair is accepted and completed.",
      "zh-Hant": "我們會回覆寄送指示、評估問題，並在繼續作業前提供維修方案與報價。若您接受並完成所提修復，運費可予以免除。"
    }
  },
  {
    "id": "pid-tuning",
    "order": 2,
    "visible": true,
    "icon": "sliders",
    "enquiryForm": "general",
    "title": {
      "en": "PID tuning service",
      "zh-Hant": "PID 調校服務"
    },
    "summary": {
      "en": "A structured tuning session for refining flight behaviour around your drone, components, and intended flying environment.",
      "zh-Hant": "有系統的調校課程，用以優化您的無人機、其零件與預期飛行環境下的飛行表現。"
    },
    "duration": {
      "en": "2–4 hours, including setup and test flight.",
      "zh-Hant": "2–4 小時，包含設定與試飛。"
    },
    "pricing": {
      "en": "Quoted after a build review; parts or venue costs are separate.",
      "zh-Hant": "於機體檢視後報價；零件或場地費用另計。"
    },
    "image": "/manus-storage/pidtuningthumb_fcb394b2.jpeg",
    "imageAlt": {
      "en": "Betaflight Blackbox Viewer traces used during a PID tuning review",
      "zh-Hant": "PID 調校檢視時使用的 Betaflight Blackbox Viewer 數據曲線"
    },
    "body": {
      "en": "Bring an existing build or a technical brief, then define a practical tuning and test path.",
      "zh-Hant": "請帶現有機體或技術簡報，接著一同設定實務調校與測試流程。"
    }
  },
  {
    "id": "drone-building-course",
    "order": 3,
    "visible": true,
    "icon": "wrench",
    "enquiryForm": "general",
    "title": {
      "en": "Drone Building Course / Coaching Sessions",
      "zh-Hant": "無人機組裝課程／指導課程"
    },
    "summary": {
      "en": "Hands-on building guidance covering component selection, assembly workflow, basic checks, and confident workshop habits.",
      "zh-Hant": "實務組裝指導，涵蓋零件選擇、裝配流程、基本檢查與良好的工作坊習慣，讓您更有信心。"
    },
    "duration": {
      "en": "Half-day workshop; multi-session formats are available.",
      "zh-Hant": "半天工作坊；亦提供多堂次課程形式。"
    },
    "pricing": {
      "en": "Quoted by group size, required parts, and workshop format.",
      "zh-Hant": "依據團隊人數、所需零件與工作坊形式報價。"
    },
    "image": "/manus-storage/Competition-readydecisionlayerthumb_b7c645e2.jpeg",
    "imageAlt": {
      "en": "Competition-ready drone-sports field with ball drones prepared for play",
      "zh-Hant": "已準備好球形無人機的競賽級無人機運動場地"
    },
    "body": {
      "en": "Designed for learners who want to understand what sits behind a dependable drone build.",
      "zh-Hant": "為想了解打造可靠無人機背後原理的學員而設。"
    }
  },
  {
    "id": "advanced-adult-course",
    "order": 4,
    "visible": true,
    "icon": "graduation",
    "enquiryForm": "general",
    "title": {
      "en": "Advanced drone course for adults",
      "zh-Hant": "成人進階無人機課程"
    },
    "summary": {
      "en": "A focused course for adult learners ready to build stronger technical judgement, controlled flight practice, and operational confidence.",
      "zh-Hant": "針對成人學員的進階課程，強化技術判斷、受控飛行練習與操作信心。"
    },
    "duration": {
      "en": "One full day or a multi-session course, depending on objectives.",
      "zh-Hant": "一整天或多堂次課程，視目標而定。"
    },
    "pricing": {
      "en": "Quoted by group size, venue, and selected training modules.",
      "zh-Hant": "依團隊規模、場地與所選訓練模組報價。"
    },
    "image": "/manus-storage/advancedronecourseforadultthumb_193b4cb1.jpeg",
    "imageAlt": {
      "en": "Adult learners practising drone flight in a workshop setting",
      "zh-Hant": "成人學員在工作坊中練習無人機飛行"
    },
    "body": {
      "en": "Course structure and prerequisites can be shaped around the group’s existing experience and objectives.",
      "zh-Hant": "課程架構與先決條件可依團隊既有經驗與目標量身調整。"
    }
  },
  {
    "id": "drone-photo-cinematography",
    "order": 5,
    "visible": true,
    "icon": "camera",
    "enquiryForm": "general",
    "title": {
      "en": "Drone Photo / Cinematography",
      "zh-Hant": "無人機攝影／航拍製作"
    },
    "summary": {
      "en": "Plan and capture professional drone photography and video for events, facilities, campaigns, and technical storytelling.",
      "zh-Hant": "為活動、場地、宣傳企劃及技術敘事規劃與拍攝專業無人機照片及影片。"
    },
    "duration": {
      "en": "Scoped by the filming plan, event schedule, locations, and requested delivery format.",
      "zh-Hant": "按拍攝計劃、活動時間表、地點及所需交付格式界定。"
    },
    "pricing": {
      "en": "Quoted by the required crew, filming time, locations, deliverables, and usage scope.",
      "zh-Hant": "按所需團隊、拍攝時數、地點、交付內容及使用範圍報價。"
    },
    "image": "/media/dronecinematography_894d41bd.jpeg",
    "imageAlt": {
      "en": "Drone cinematography equipment prepared for a waterfront filming setup",
      "zh-Hant": "為海濱拍攝準備的無人機航拍設備"
    },
    "body": {
      "en": "Define the filming objective, location, required permissions, capture plan, and delivery format around your event or communications brief.",
      "zh-Hant": "根據您的活動或傳訊需求，釐定拍攝目標、地點、所需許可、拍攝計劃與交付格式。"
    }
  }
];
