import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = path.join(projectRoot, "content", "products");
const outputPath = path.join(projectRoot, "client", "src", "lib", "productContent.generated.ts");

type ProductContent = {
  familyId: string;
  title: { en: string; "zh-Hant": string };
  description: { en: string; "zh-Hant": string };
};

function parseProduct(source: string): ProductContent {
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("Product Markdown is missing frontmatter");
  const metadata: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    metadata[line.slice(0, separator).trim()] = line.slice(separator + 1).trim();
  }
  const required = ["familyId", "title.en", "title.zh-Hant", "description.en", "description.zh-Hant"];
  for (const key of required) {
    if (!metadata[key]) throw new Error(`Product Markdown is missing ${key}`);
  }
  const sections = match[2].split(/^<!--\s*locale:(en|zh-Hant)\s*-->\s*$/m);
  const body = { en: "", "zh-Hant": "" };
  for (let index = 1; index < sections.length; index += 2) {
    const language = sections[index] as "en" | "zh-Hant";
    body[language] = sections[index + 1].trim();
  }
  if (body.en !== metadata["description.en"] || body["zh-Hant"] !== metadata["description.zh-Hant"]) {
    throw new Error(`Product ${metadata.familyId} body must match its description metadata`);
  }
  return {
    familyId: metadata.familyId,
    title: { en: metadata["title.en"], "zh-Hant": metadata["title.zh-Hant"] },
    description: { en: metadata["description.en"], "zh-Hant": metadata["description.zh-Hant"] },
  };
}

const filenames = (await readdir(contentRoot)).filter((filename) => filename.endsWith(".md")).sort();
const products = (await Promise.all(filenames.map(async (filename) => parseProduct(await readFile(path.join(contentRoot, filename), "utf8")))))
  .sort((a, b) => a.familyId.localeCompare(b.familyId));

await writeFile(outputPath, `// Generated by scripts/generate-product-data.mts. Edit Markdown files under content/products instead.\nexport const productContent = ${JSON.stringify(products, null, 2)} as const;\n`, "utf8");
console.log(`Generated ${products.length} product content record(s).`);
