import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = path.join(projectRoot, "content", "services");
const outputPath = path.join(projectRoot, "client", "src", "lib", "serviceContent.generated.ts");

type Language = "en" | "zh-Hant";
type Localized = { en: string; "zh-Hant": string };
type ServiceContent = {
  id: string;
  order: number;
  visible: boolean;
  icon: string;
  enquiryForm: "repair" | "general";
  title: Localized;
  summary: Localized;
  duration: Localized;
  pricing: Localized;
  image: string;
  imageAlt: Localized;
  body: Localized;
};

const icons = ["wrench", "sliders", "graduation", "camera"];

function parseService(rawSource: string, file: string): ServiceContent {
  const source = rawSource.replace(/\r\n/g, "\n");
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${file}: missing the --- frontmatter --- block at the top`);
  const metadata: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    if (line.trim().startsWith("#")) continue;
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    metadata[line.slice(0, separator).trim()] = line.slice(separator + 1).trim();
  }
  const required = ["id", "title.en", "title.zh-Hant", "summary.en", "summary.zh-Hant", "image"];
  for (const key of required) {
    if (!metadata[key]) throw new Error(`${file}: "${key}" is required`);
  }
  const sections = match[2].split(/^<!--\s*locale:(en|zh-Hant)\s*-->\s*$/m);
  const body: Localized = { en: "", "zh-Hant": "" };
  for (let index = 1; index < sections.length; index += 2) {
    body[sections[index] as Language] = sections[index + 1].trim();
  }
  if (!body.en || !body["zh-Hant"]) throw new Error(`${file}: add both <!-- locale:en --> and <!-- locale:zh-Hant --> description sections`);
  const order = metadata.order ? Number(metadata.order) : 999;
  if (!Number.isFinite(order)) throw new Error(`${file}: order must be a number`);
  const icon = (metadata.icon || "wrench").toLowerCase();
  if (!icons.includes(icon)) throw new Error(`${file}: icon must be one of ${icons.join(", ")}`);
  const localized = (key: string): Localized => ({ en: metadata[`${key}.en`] ?? "", "zh-Hant": metadata[`${key}.zh-Hant`] || metadata[`${key}.en`] || "" });

  return {
    id: metadata.id,
    order,
    visible: (metadata.visible ?? "true").toLowerCase() !== "false",
    icon,
    enquiryForm: metadata.enquiryForm === "repair" ? "repair" : "general",
    title: localized("title"),
    summary: localized("summary"),
    duration: localized("duration"),
    pricing: localized("pricing"),
    image: metadata.image,
    imageAlt: localized("imageAlt"),
    body,
  };
}

const filenames = (await readdir(contentRoot)).filter((filename) => filename.endsWith(".md")).sort();
const services = (await Promise.all(filenames.map(async (filename) => parseService(await readFile(path.join(contentRoot, filename), "utf8"), `content/services/${filename}`))))
  .sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));

const ids = new Set<string>();
for (const service of services) {
  if (ids.has(service.id)) throw new Error(`Duplicate service id "${service.id}"`);
  ids.add(service.id);
}

await writeFile(outputPath, `// Generated by scripts/generate-service-data.mts. Edit Markdown files under content/services instead.
export type ServiceContentRecord = {
  id: string;
  order: number;
  visible: boolean;
  icon: string;
  enquiryForm: "repair" | "general";
  title: { en: string; "zh-Hant": string };
  summary: { en: string; "zh-Hant": string };
  duration: { en: string; "zh-Hant": string };
  pricing: { en: string; "zh-Hant": string };
  image: string;
  imageAlt: { en: string; "zh-Hant": string };
  body: { en: string; "zh-Hant": string };
};
export const serviceContent: readonly ServiceContentRecord[] = ${JSON.stringify(services, null, 2)};
`, "utf8");
console.log(`Generated ${services.length} service content record(s).`);
