import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = path.join(projectRoot, "content", "blog");
const outputPath = path.join(projectRoot, "client", "src", "lib", "blog.generated.ts");

type BlogPost = {
  slug: string;
  publishedAt: string;
  updatedAt?: string;
  author: string;
  coverImage: string;
  title: { en: string; "zh-Hant": string };
  description: { en: string; "zh-Hant": string };
  category: { en: string; "zh-Hant": string };
  body: { en: string; "zh-Hant": string };
};

function parseFrontmatter(source: string) {
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("Blog article is missing frontmatter");
  const metadata: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    metadata[line.slice(0, separator).trim()] = line.slice(separator + 1).trim();
  }
  const sections = match[2].split(/^<!--\s*locale:(en|zh-Hant)\s*-->\s*$/m);
  const body = { en: "", "zh-Hant": "" };
  for (let index = 1; index < sections.length; index += 2) {
    const language = sections[index] as "en" | "zh-Hant";
    body[language] = sections[index + 1].trim();
  }
  const required = ["slug", "publishedAt", "author", "coverImage", "title.en", "title.zh-Hant", "description.en", "description.zh-Hant", "category.en", "category.zh-Hant"];
  for (const key of required) {
    if (!metadata[key]) throw new Error(`Blog article is missing ${key}`);
  }
  if (!body.en || !body["zh-Hant"]) throw new Error(`Blog article ${metadata.slug} needs both locale sections`);
  return {
    slug: metadata.slug,
    publishedAt: metadata.publishedAt,
    ...(metadata.updatedAt ? { updatedAt: metadata.updatedAt } : {}),
    author: metadata.author,
    coverImage: metadata.coverImage,
    title: { en: metadata["title.en"], "zh-Hant": metadata["title.zh-Hant"] },
    description: { en: metadata["description.en"], "zh-Hant": metadata["description.zh-Hant"] },
    category: { en: metadata["category.en"], "zh-Hant": metadata["category.zh-Hant"] },
    body,
  } satisfies BlogPost;
}

const filenames = (await readdir(contentRoot)).filter((filename) => filename.endsWith(".md")).sort();
const posts = (await Promise.all(filenames.map(async (filename) => parseFrontmatter(await readFile(path.join(contentRoot, filename), "utf8")))))
  .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));

await writeFile(outputPath, `// Generated by scripts/generate-blog-data.mts. Edit Markdown files under content/blog instead.\nexport const blogPosts = ${JSON.stringify(posts, null, 2)} as const;\n`, "utf8");
console.log(`Generated ${posts.length} blog post(s).`);
