import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = path.join(projectRoot, "content", "policies");
const outputPath = path.join(projectRoot, "client", "src", "lib", "policyContent.generated.ts");
const pages = ["legal", "sales"] as const;

type PolicyContent = {
  id: string;
  page: (typeof pages)[number];
  order: number;
  title: { en: string; "zh-Hant": string };
  subtitle: string;
  version: string;
  effective: string;
  body: string;
};

function parsePolicy(rawSource: string, file: string): PolicyContent {
  const source = rawSource.replace(/\r\n/g, "\n");
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${file}: missing the --- frontmatter --- block at the top`);
  const metadata: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    if (line.trim().startsWith("#")) continue;
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    metadata[line.slice(0, separator).trim()] = line.slice(separator + 1).trim();
  }
  for (const key of ["id", "page", "title.en", "version", "effective"]) {
    if (!metadata[key]) throw new Error(`${file}: "${key}" is required`);
  }
  if (!/^[a-z0-9-]+$/.test(metadata.id)) throw new Error(`${file}: id must use lowercase letters, numbers and hyphens (it becomes the link anchor)`);
  if (!pages.includes(metadata.page as (typeof pages)[number])) throw new Error(`${file}: page must be one of ${pages.join(", ")}`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(metadata.effective)) throw new Error(`${file}: effective must be a date like 2026-10-04`);
  const body = match[2].trim();
  if (!body) throw new Error(`${file}: the policy text is empty`);
  const order = metadata.order ? Number(metadata.order) : 999;
  if (!Number.isFinite(order)) throw new Error(`${file}: order must be a number`);
  return {
    id: metadata.id,
    page: metadata.page as (typeof pages)[number],
    order,
    title: { en: metadata["title.en"], "zh-Hant": metadata["title.zh-Hant"] || metadata["title.en"] },
    subtitle: metadata["subtitle.en"] ?? "",
    version: metadata.version,
    effective: metadata.effective,
    body,
  };
}

const filenames = (await readdir(contentRoot)).filter((filename) => filename.endsWith(".md")).sort();
const policies = (await Promise.all(filenames.map(async (filename) => parsePolicy(await readFile(path.join(contentRoot, filename), "utf8"), `content/policies/${filename}`))))
  .sort((a, b) => a.page.localeCompare(b.page) || a.order - b.order || a.id.localeCompare(b.id));

const ids = new Set<string>();
for (const policy of policies) {
  if (ids.has(policy.id)) throw new Error(`Duplicate policy id "${policy.id}"`);
  ids.add(policy.id);
}
for (const page of pages) {
  if (!policies.some((policy) => policy.page === page)) throw new Error(`content/policies: no documents for the "${page}" page`);
}

await writeFile(outputPath, `// Generated by scripts/generate-policy-data.mts. Edit Markdown files under content/policies instead.
export type PolicyContentRecord = {
  id: string;
  page: "legal" | "sales";
  order: number;
  title: { en: string; "zh-Hant": string };
  subtitle: string;
  version: string;
  effective: string;
  body: string;
};
export const policyContent: readonly PolicyContentRecord[] = ${JSON.stringify(policies, null, 2)};
`, "utf8");
console.log(`Generated ${policies.length} policy record(s).`);
